### ISSUE TITLE
Support for HTTP proxy to Google/Apple servers

### ISSUE THREAD

**Issue by JensRantil** [appleboy/gorush#108]

**Comment by appleboy** [comment]
@JensRantil I will take it.

**Comment by appleboy** [comment]
`http_proxy` property only working for `GCM`. `APNS` doesn't support http proxy setting, because `APNS` using golang `http2` library.

**Comment by appleboy** [comment]
Please try v1.6.0 version.

https://github.com/appleboy/gorush/releases/tag/v1.6.0
