### ISSUE TITLE
Any way to get bad/invalid device tokens?

### ISSUE THREAD

**Issue by justinlu** [appleboy/gorush#109]
The APNS HTTP/2 will report bad/invalid device tokens. I think we should removed those invalid tokens from DB to prevent from sending them again and again.

Is there a way to get those from gorush API?

Thanks

**Comment by chekalskiy** [comment]
Same question about GCM. Maybe add a callback to reporting about bad tokens?

**Comment by codepushr** [comment]
APNS has (had?) a feedback channel and GCM already sends the invalid tokens directly back in the response - one has to check the `NotRegistered` error in the result.

**Comment by andreyser** [comment]
To get APNS bad tokens I made a pull request - https://github.com/appleboy/gorush/pull/175

**Comment by gebv** [comment]
Can be a callback method via post custom method?
```
notify_of_error=http://172.16.0.23/listener_errors
```
Or via amqp\nsq or ws?

**Comment by appleboy** [comment]
I will implement the sync mode so you can get error message from fail push notification in API response.

**Comment by appleboy** [comment]
Release v1.8.1 https://github.com/appleboy/gorush/releases/tag/v1.8.1

If you need error logs from sending fail notifications, please set `sync` as `true` on yaml config.

```diff
core:
  port: "8088" # ignore this port number if auto_tls is enabled (listen 443).
  worker_num: 0 # default worker number is runtime.NumCPU()
  queue_num: 0 # default queue number is 8192
  max_notification: 100
- sync: false 
+ sync: true
```

See the following error format.

```json
{
  "counts": 60,
  "logs": [
    {
      "type": "failed-push",
      "platform": "android",
      "token": "*******",
      "message": "Hello World Android!",
      "error": "InvalidRegistration"
    },
    {
      "type": "failed-push",
      "platform": "ios",
      "token": "*****",
      "message": "Hello World iOS1111!",
      "error": "Post https://api.push.apple.com/3/device/bbbbb: remote error: tls: revoked certificate"
    },
    {
      "type": "failed-push",
      "platform": "ios",
      "token": "*******",
      "message": "Hello World iOS222!",
      "error": "Post https://api.push.apple.com/3/device/token_b: remote error: tls: revoked certificate"
    }
  ],
  "success": "ok"
}
```
