### ISSUE TITLE
ERROR: Cannot unmarshal DNS Message

### ISSUE THREAD

**Issue by wsoula** [appleboy/gorush#116]
Trying to run the gorush container in our environment when I post to it with:

```
curl -v -XPOST 10.141.3.136:32772/api/push -d '{"notifications":[{"tokens":["990004543798742"],"platform":2,"message":"Hello Android"}]}'
```

I get error: 

```
ERRO[2016/08/03 - 14:24:34] GCM server error: error sending request to GCM HTTP server: error sending request to HTTP connection server>Post https://gcm-http.googleapis.com/gcm/send: dial tcp: lookup gcm-http.googleapis.com on 10.141.3.136:53: cannot unmarshal DNS message
```

Googling for the error talks a lot about go versions less than 1.6 and consul and netgo.  From what I can tell gorush is using go > 1.6, but we are using consul in our environment.  That token in my above command probably does not exist but I would expect a different error for that.

Can you help point me in the right direction to get this working.  I'm kind of at a loss on how to debug this further.  Thanks in advance.

**Comment by wsoula** [comment]
Using the regular dns for this container instead of consul dns allows we to workaround this issue.  I had to change our depoyment to allow specifying dns and I have moved forward.  Would be nice to know where this should be fixed for real.

**Comment by appleboy** [comment]
Can't reproduce this issue.
