### ISSUE TITLE
Queue backends

### ISSUE THREAD

**Issue by chriswessels** [appleboy/gorush#125]
Are any persistent backends available for the queuing functionality?

I'd like to persist the queue to ensure a low possibility of data loss and Redis would be ideal.

Thanks!

**Comment by lunny** [comment]
Or nsq as a backend.

**Comment by chriswessels** [comment]
+1 for nsq. That would be excellent.

**Comment by yacir** [comment]
@appleboy any updates for this feature?

**Comment by appleboy** [comment]
We will support different queues as a backend. like

* AWS SQS
* nats
* nsq
* simple channel (default.)

I have implemented the worker interface in https://github.com/appleboy/gorush/pull/589

**Comment by appleboy** [comment]
Gorush supports NSQ and NATS in the `master` branch now. See the detailed information: https://github.com/appleboy/gorush/issues/599
