### ISSUE TITLE
Loading stats pages causes the server to wait for open connections during shutdown

### ISSUE THREAD

**Issue by serg472** [appleboy/gorush#143]
If I open `http://localhost:8088/api/stat/app` and then attempt to shutdown the server with `Ctrl+C`, it won't shutdown immediately and will wait around 30s for some open connections (even after I close the browser). This happens only if I retrieve the stats page, usually it shuts down right away.

```
24352 Received SIGINT.
24352 [::]:8088 Listener closed.
24352 Waiting for connections to finish...
--(this takes about 30s)--
[STOP - Hammer Time] Forcefully shutting down parent
```

**Comment by appleboy** [comment]
@serg472 Please download binary for [v1.7.3 version](https://github.com/appleboy/gorush/releases/tag/v1.7.3).
