### ISSUE TITLE
Support set the value of badge to 0 to remove the iOS badge number

### ISSUE THREAD

**Issue by minchao** [appleboy/gorush#147]
Refer to the following [code](https://github.com/appleboy/gorush/blob/master/gorush/notification.go#L307): When the badge is 0, It will never create the badge field in payload.

```go
	if req.Badge > 0 {
		payload.Badge(req.Badge)
	}
```

An option is use pointers for omitempty fields, since that allows a clear distinction between "unset" (nil) and "empty" (non-nil, zero value).

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Change

```go
	if req.Badge > 0 {
		payload.Badge(req.Badge)
	}
```

to 

```go
	if req.Badge >= 0 {
		payload.Badge(req.Badge)
	}
```

**Comment by appleboy** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html

ref: `Configuring a Silent Notification` section
