### ISSUE TITLE
ios notification is not working with tile.

### ISSUE THREAD

**Issue by TianDaGe** [appleboy/gorush#162]
```
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "message": "Hello World iOS!"
    }
  ]
}
```
This is working.

```
"notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "message": "Hello World iOS!",
      "title": "You got message"
    }
  ]
```
but this is not working with title.

Merry Xmas!
Thanks for your support again

**Comment by TianDaGe** [comment]
@appleboy  I found reason why ios title is not working.
ios notification type is like that. that is default. gorush is sending like that.
`{"aps":{"alert":"message"}}`
but if we will need title, alert type must be like that
`{"aps":{"alert":{"body":"message", "title":"title"}}}`
Looking forward to hearing from you soon

**Comment by TianDaGe** [comment]
@appleboy  so I have just checked your source project.
currently, to show title on platform, we can do like this.
```
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "title": "title",
      "alert": {"body": "message"}
    }
  ]
}
```
or we can user subtitle of alert instead of title.
```
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "alert": {
            "body": "message",
            "subtitle": "title"
      }
    }
  ]
}
```
I think, gorush has to not use message field on ios platform.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
You can try the following example:

https://github.com/appleboy/gorush#ios-example

```json
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "badge": 5,
      "alert": {
        "title" : "Game Request",
        "body" : "Bob wants to play poker",
        "action-loc-key" : "PLAY"
      }
    }
  ]
```

**Comment by TianDaGe** [comment]
@appleboy I got it.
good work. did you publish released version?

**Comment by appleboy** [comment]
Bumping version now. Please wait.

**Comment by TianDaGe** [comment]
And then, I have one request for gorush.
currently, same badge could be selected on every devices. but in the development, every device's badges will be different. I think, badge will be included in data, so developers can use badge on every devices differently. Actually, android platform has not badge field. That is only my asking, anyway gorush is perfect meanwhile using.

**Comment by appleboy** [comment]
@TianDaGe Please try it.

https://github.com/appleboy/gorush/releases/tag/v1.7.2

**Comment by appleboy** [comment]
Please let me know it is working or not. Thanks.

**Comment by TianDaGe** [comment]
@appleboy I have just checked v1.7.2
ios platform is working fine. but android platform is not working
I have checked with title and with out title. and I have checked v1.7.1 again. v1.7.1 is working fine

**v1.7.1**
```
[37mDEBU[0m[2016/12/24 - 16:48:41] Start push notification for Android
[37mDEBU[0m[2016/12/24 - 16:48:41] Android Success count: 1, Failure count: 0
[34mINFO[0m[2016/12/24 - 16:48:41] |[97;42m succeeded-push [0m| [97;43mandroid[0m [**********M:APA91bGNkfSdVZ79tFl9uomyEYYSR-TI25i2C6v-pIXoJqxpk1pHXVs2kUaH9PVeG-AeiNPIrEZIKJ0xC6MJ_wp1sh0cb1apX9C_M1_BF_fEAteYILtfxe8F9aawJE72KV**********] message test.
```

**v1.7.2**
```
time="2016/12/24 - 16:49:03" level=debug msg="Start push notification for Android"
time="2016/12/24 - 16:49:04" level=error msg="GCM server error: error sending request to GCM HTTP server: error unmarshaling json from body: json: cannot unmarshal number 4698167438340355184 into Go value of type int"
```

my request param is as follow
```
{"notifications":[
	{
		"tokens":["token"],
		"platform":2,
		"message":"message test."
	}
	]
}
```

**Comment by appleboy** [comment]
v1.7.2 is working for android platform.

<img width="929" alt="screen shot 2016-12-24 at 5 11 43 pm" src="https://cloud.githubusercontent.com/assets/21979/21466215/3e392d66-c9fc-11e6-9bd2-180789bb1ac4.png">

**Comment by TianDaGe** [comment]
I have checked on windows version.

**Comment by TianDaGe** [comment]
@appleboy I have just checked on linux verison.
That is working fine on both platform. but as I checked, window version really is not working on android platform.

**Comment by appleboy** [comment]
I will try the windows version later.

**Comment by TianDaGe** [comment]
thanks, looking forward to hearing from you soon.

**Comment by TianDaGe** [comment]
one more, when i finish gorush listen on linux, it is not finished immediately

I have just pressed Ctrl+C, and i pressed several times after this. but service is not finished immediately.
v1.7.1 was working fine.
```
^C3751 Received SIGINT.
3751 [::]:8088 Listener closed.
3751 Waiting for connections to finish...
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
^C3751 Received SIGINT.
[STOP - Hammer Time] Forcefully shutting down parent
3751 Serve() returning...

```

**Comment by appleboy** [comment]
v1.7.2 is also working on window-amd64.

<img width="664" alt="screen shot 2016-12-24 at 5 35 09 pm" src="https://cloud.githubusercontent.com/assets/21979/21466284/987d1e24-c9ff-11e6-9b77-d509944e64a5.png">

**Comment by TianDaGe** [comment]
perhaps, do i need go get again?
`$ go get -u -v github.com/appleboy/gorush`

**Comment by appleboy** [comment]
No, I just download the binary from https://github.com/appleboy/gorush/releases/tag/v1.7.2

You don't need any Go environments.

**Comment by TianDaGe** [comment]
hahaha
@appleboy  window version is working fine.
I checked with gorush-v1.7.2-windows-386.exe. sorry for now,
