### ISSUE TITLE
Support empty notification for android

### ISSUE THREAD

**Issue by cymonn** [appleboy/gorush#169]
Using FCM, I found that we need to send only `data` part **(except `notification` part)**, to android device to receive the notification even if our app is in background.
But gorush always includes notification part because of code below.
```
// Set request message if body is empty
if len(notification.Notification.Body) == 0 {
	notification.Notification.Body = req.Message
}
```
Can you please support empty notification part?
For more help, see example.

I found `onMessageReceived()` is **not** called when sending the both parts.
```
{
  "registration_ids":["TOKEN"],
  "data": {
    "key1": "foo"
   },
  "notification": {
    "body": "Hello World!"
  }
}
```

But, it is called when sending only data part.
```
{
  "registration_ids":["TOKEN"],
  "data": {
    "key1": "foo"
   }
}
```

Or, empty notification object can be acceptable (`onMessageReceived()` triggered)
```
{
  "registration_ids":["TOKEN"],
  "data": {
    "key1": "foo"
   },
  "notification": { }
}
```

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
I will bump to next version.

**Comment by tcolepc** [comment]
Testing gorush v1.8.1, we receive the notification, including the "notification field", although  json notification was empty or nonexistent
`"notification": { }`

We need that field not to arrive, so I can wake up the app.
