### ISSUE TITLE
POST api/push result success but no push notification send

### ISSUE THREAD

**Issue by namkazt** [appleboy/gorush#193]
i was test with command : 
gorush -ios -m="xx" -t="xxx" -i="xxx"
push notificaiton was sent success and display on device
DEBU[2017/03/01 - 07:22:14] Start push notification for iOS
INFO[2017/03/01 - 07:22:14] | succeeded-push | ios [**********5441204dd930405440733e8821d425262e16414dc7d8**********] test

but when i try to use web api. it result success but do not got any notificaiton on device.
{
  "success": "ok"
}

log: 
INFO[2017/03/01 - 07:27:42] | header | POST /api/push 14.188.3.41 application/x-www-form-urlencoded Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
[GIN] 2017/03/01 - 07:27:42 | 200 |     215.432µs | 14.188.3.41 |   POST    /api/push

**Comment by appleboy** [comment]
@namkazt Could you provide you JSON data?

**Comment by namkazt** [comment]
Hi @appleboy  thanks for fast reppy

here is JSON data: 

{ "notifications": [ { "tokens": ["XXXXXXXXXX5441204dd930405440733e8821d425262e16414dXXXXXXXXX"], "platform": 1, "message": "Hello World iOS!"} ] }

**Comment by namkazt** [comment]
is there any wrong when i using Postman to test it ?
![2211](https://cloud.githubusercontent.com/assets/6035916/23450365/59e2c0ac-fe8d-11e6-8726-2ad93288be99.png)

**Comment by appleboy** [comment]
What is your console message?

```
INFO[2017/03/01 - 07:27:42] | header | POST /api/push 14.188.3.41 application/x-www-form-urlencoded Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
[GIN] 2017/03/01 - 07:27:42 | 200 | 215.432µs | 14.188.3.41 | POST /api/push
```

**Comment by namkazt** [comment]
Only this 
![cw](https://cloud.githubusercontent.com/assets/6035916/23450533/4514caa2-fe8e-11e6-8a17-ded45f0c913d.png)

**Comment by namkazt** [comment]
App Info : 
// 20170301143820
// http://174.129.117.128:8088/api/stat/app

{
  "version": "v1.7.4",
  "queue_max": 0,
  "queue_usage": 0,
  "total_count": 0,
  "ios": {
    "push_success": 0,
    "push_error": 0
  },
  "android": {
    "push_success": 0,
    "push_error": 0
  }
}

**Comment by namkazt** [comment]
is there any way to see the error or something ?

**Comment by namkazt** [comment]
@appleboy i got it working right now. maybe i do not set 
worker_num: 0 # default worker number is runtime.NumCPU()
queue_num: 0 # default queue number is 8192

when i set it to 
worker_num: 1 # default worker number is runtime.NumCPU()
queue_num: 10000 # default queue number is 8192

it working

**Comment by appleboy** [comment]
@namkazt I will check `worker_num` setting.

What is your OS?

**Comment by namkazt** [comment]
version: GoRush v1.7.4, Compiler: gc go1.7.4, Copyright (C) 2016 Bo-Yi Wu, Inc.
server: Ubuntu-trusty-14.04-amd64-server-20170110 (ami-50e64d33)

**Comment by appleboy** [comment]
@namkazt `v1.7.4` doesn't support default value if user set `worker_num` or `queue_num ` to zero.

See the commit: https://github.com/appleboy/gorush/commit/962c033246d9118e4d29fbe212da4e2b469ad33f

See the `v1.7.4` document here: https://github.com/appleboy/gorush/tree/v1.7.4#features
