### ISSUE TITLE
Can I get the push data

### ISSUE THREAD

**Issue by mrchenhao** [appleboy/gorush#211]
Can I get the information about the push I send before. success or failed?

**Comment by appleboy** [comment]
@mrchenhao I will implement the sync mode so you can get error message from fail push notification in API response.

**Comment by appleboy** [comment]
duplicated of https://github.com/appleboy/gorush/issues/109

**Comment by appleboy** [comment]
https://github.com/appleboy/gorush/issues/109#issuecomment-292858157 get error message from fail push notification in API response.
