### ISSUE TITLE
leveldb logs

### ISSUE THREAD

**Issue by MoonshineSG** [appleboy/gorush#238]
the LOG file for the leveldb grows very very fast... is there a way to trim it or keep it under a limited size ?

**Comment by appleboy** [comment]
@MoonshineSG maybe we should implement the Cron job for file rotation

**Comment by MoonshineSG** [comment]
sorry, not really familiar with how levedb works... the LOG file is simple a logfile which can be manually removed (and then it would be created again, empty) ? 
if thats the case, cron would be the easy solution...

**Comment by appleboy** [comment]
>  the LOG file is simple a logfile which can be manually removed (and then it would be created again, empty) ?

Yes.

**Comment by MoonshineSG** [comment]
then, there no need to do anything on your side.. I'll just create a `logrotate` config and set my own rules. Thanks!
