### ISSUE TITLE
How to send notification to a webapp?

### ISSUE THREAD

**Issue by thanhngvpt** [appleboy/gorush#257]
Hi all.
I want to send notification to a webapp not mobile. Can i use gorush?
Many thanks.

**Comment by appleboy** [comment]
@thanhngvpt I think your app needs to support [andriod client](https://firebase.google.com/docs/cloud-messaging/android/client) or [iOS client](https://www.appcoda.com/push-notification-ios/) before using gorush。

Please read the above links. Thanks.

**Comment by thanhngvpt** [comment]
Thanks @appleboy But now My web app have an notification like a mail box, I don't know which fit me, Can you suggest me?

**Comment by appleboy** [comment]
@thanhngvpt Are you an android or ios developer? Maybe you can send the above link to Android or iso developer. I think they understand what the link meant.

**Comment by appleboy** [comment]
We don't support web App.
