### ISSUE TITLE
Feature request: populate CollapseID field in apns2 Notification struct

### ISSUE THREAD

**Issue by oadk** [appleboy/gorush#307]
Hi,

Thank you for making gorush!

I have a small request: the apns2 library supports the CollapseID field for notifications. See [here:](https://github.com/sideshow/apns2/blob/f06de67a6ba682db5b5947925c0d2e747108e7fb/notification.go)

```	
	// A string which allows multiple notifications with the same collapse identifier
	// to be displayed to the user as a single notification. The value should not
	// exceed 64 bytes.
	CollapseID string
```

Currently in gorush, the `CollapseKey` is only passed on to Android. Please could we use this value when creating the `apns2.Notification` struct in `GetIOSNotification()` ?

Thanks :)

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Implementation in #308

**Comment by oadk** [comment]
Thank you for making the change, and thank you for doing it so quickly :)

**Comment by johan-lejdung** [comment]
is this translated to `apns-collapse-id`? Maybe the documentation should be updated as well

**Comment by appleboy** [comment]
Where need to be updated in the documentation?

https://github.com/sideshow/apns2/blob/c6554aff77e6e5580dec977c8c33cc238f329ab0/client.go#L202-L204

**Comment by johan-lejdung** [comment]
For the Gorush project, there is no mention of the collapse_id in the README
