### ISSUE TITLE
Automatically determine platform?

### ISSUE THREAD

**Issue by AmarOk1412** [appleboy/gorush#311]
I don't know if it's possible, but something would be great`is to have:

```json
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "message": "Hello World Automatic platform!"
    }
  ]
}
```

instead of:

```json
{
  "notifications": [
    {
      "tokens": ["token_a", "token_b"],
      "platform": 1,
      "message": "Hello World iOS!"
    }
  ]
}
```

**Comment by appleboy** [comment]
I think it is not possible unless we can define what is different between Apns and android token.

**Comment by AmarOk1412** [comment]
Yeah that's what I think too. And I'm not sure about the difference of the 2 formats.
