### ISSUE TITLE
Static release instead of dynamic binaries?

### ISSUE THREAD

**Issue by AmarOk1412** [appleboy/gorush#312]
For gorush-1.10.0-linux-amd64, we can found a dynamic binaries in https://github.com/appleboy/gorush/releases

So we must relink the binary with musl manually (see `ldd gorush`)

**Comment by appleboy** [comment]
See https://github.com/appleboy/gorush/blob/master/Makefile#L167 and https://github.com/appleboy/gorush/blob/master/Makefile#L23

**Comment by AmarOk1412** [comment]
Yeah yeah I just talk about binaries in the release page. Sure we can rebuild a static bin.

**Comment by michaelpjohnson** [comment]
Rather than create a new Issue, I want to resurrect this one. The last release on the release page was in July 2020. Do you (@appleboy) have plans to make more formal releases in the future? There are many bug fixes etc in the `main` branch since July 2020.

**Comment by appleboy** [comment]
@michaelpjohnson released https://github.com/appleboy/gorush/releases/tag/v1.14.0

**Comment by michaelpjohnson** [comment]
You rock @appleboy ! Thanks
