### ISSUE TITLE
Option to specify topic for APNS

### ISSUE THREAD

**Issue by jaisontj** [appleboy/gorush#342]
When using certificates which support multiple topics, it is mandatory to specify the `apns-topic` as a header in the request. Could you have an option to do this ?

**Comment by jaisontj** [comment]
I see that this has been done [here](https://github.com/appleboy/gorush/issues/67)

Could you add this in the docs as well ?

**Comment by appleboy** [comment]
I already updated the docs before you create this issue.

**Comment by jaisontj** [comment]
Oh, could you tell me where this is specified ? I have fixed the issue by re-creating my certificates and ensure that it only supports a single topic.

Is it the topic specified in [this](https://github.com/appleboy/gorush#request-body) table ?

**Comment by appleboy** [comment]
Please reopen the issue if you still have this problem.
