### ISSUE TITLE
What is lambda main handler?

### ISSUE THREAD

**Issue by parangdae** [appleboy/gorush#343]
Upload the deployment.zip via web UI and function-name gorush.
handler name : server_lambda, main, gorush, server are failed

Execution result: failed
{
  "errorMessage": "fork/exec /var/task/server_lambda: no such file or directory",
  "errorType": "PathError"
}

**Comment by parangdae** [comment]
I found handler.
`release/linux/lambda/gorush`

**Comment by thaitanloi365** [comment]
@parangdae , what handler's name you are using ?
