### ISSUE TITLE
Wtf!!??

### ISSUE THREAD

**Issue by legion-zver** [appleboy/gorush#355]
Why can't I transfer field "data" through GRPC??!!!

**Comment by belek** [comment]
Well, even if issue does not have proper title, the problem exists :)
Is there an option of sending custom key value arguments using gRPC?

**Comment by HTechHQ** [comment]
I feel the title as well ;-)
But to get to the point, protocol buffers have a map that looks like it can do the job:
```
map<string, string> data = N;
```
https://developers.google.com/protocol-buffers/docs/proto#maps

If I see this correctly, it would be part of the `NotificationRequest` definition and could just be appended, right? 

I might be able to provide this, so let me know. Any other fields, that are missing too?

**Comment by appleboy** [comment]
Implemented in https://github.com/appleboy/gorush/pull/412
