### ISSUE TITLE
configuration problem when using aws lambda

### ISSUE THREAD

**Issue by sthkindacrazy** [appleboy/gorush#358]
after customizing config file, `confing/config.yml` , followed below lines to make binary file.

```
$ git clone https://github.com/appleboy/gorush.git
$ cd gorush && make build_linux_lambda
```

However, when checking configurations by calling `api/config` via aws gateway, config file shows default values rather than showing customized values.

**Comment by sthkindacrazy** [comment]
@appleboy  why does make file always refer to the default configuration settings?

**Comment by appleboy** [comment]
See the default config: https://github.com/appleboy/gorush/blob/251429530d2b43a6c043845957779ccd5a97622c/config/config.go#L13-L88

**Comment by sthkindacrazy** [comment]
@appleboy well, I've overrided this `config.go` with my configurations, but it shows same result.

**Comment by sthkindacrazy** [comment]
resolved issue

**Comment by zeuikli** [comment]
@sthkindacrazy What is your solution? I also encountered this problem.

**Comment by ColeTownsend** [comment]
@sthkindacrazy what was the resolution?

**Comment by appleboy** [comment]
@ColeTownsend May I ask what issues you have encountered?
