### ISSUE TITLE
Android FCM `Invalid Server Key`

### ISSUE THREAD

**Issue by sh0umik** [appleboy/gorush#361]
I have a working FCM Client that is using Firebase Messaging Server as a Backend . I can send push notification form the Firebase Console.

However i tried sending a notification ( topic subscription ) via gorush cli , I am getting `| failed-push | android [*****] | This is a Firebase Cloud Messaging Topic Message | Error Message: invalid registration token` . I am using the Server Key from Firebase App > Project Settings > Cloud Messaging > Server Key . Is it correct ?

**Comment by appleboy** [comment]
See the following screenshot.

![gorush_ _settings_ _firebase_console](https://user-images.githubusercontent.com/21979/44467544-b42bcb00-a655-11e8-84f0-423dd1b1a9db.png)

**Comment by DoubleHub** [comment]
I am getting the same error, and I can't generate a Legacy Server Key since Google disabled them in March 2020. How can I use the new Server Key with Gorush?
