### ISSUE TITLE
get 'succeed-push' but no message recieved

### ISSUE THREAD

**Issue by metrue** [appleboy/gorush#363]
I tried `gorush` with its cli binary:
```
./gorush -i cert.p12 -P <password> -ios -m "abcd" -t <device_token>
```
it return `INFO[2018/07/29 - 01:03:44] | succeeded-push | ios [**********a3a943c4324b5bc246c2ec95b67b24a9f7ced3fd2e9b**********] abcd`

but I had not received any message on my iPhone, anyone can help?

**Comment by appleboy** [comment]
@metrue Could you have to try `--production` flag for production mode?

**Comment by metrue** [comment]
somehow it's ok now.
