### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ahmedakmal525** [appleboy/gorush#369]
Hi, I developed an android application.. where I have to send push notifications to my users real time. but I have one doubt. If I use the **gorush** with **Firebase / GCM API Key** and the respective generated tokens of the devices, do i get charged for using their API key?, If the push notifications exceed the allowed limit?

**Comment by slimus** [comment]
@ahmedakmal525 please read about fcm limit [here](https://firebase.google.com/docs/cloud-messaging/concept-options#upstream_throttling)

**Comment by slimus** [comment]
I think we can close this issue @appleboy
