### ISSUE TITLE
Support for apns-collapse-id?

### ISSUE THREAD

**Issue by johan-lejdung** [appleboy/gorush#373]
Is there any support for sending the apns-collapse-id on a push notification?

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

**Comment by johan-lejdung** [comment]
@appleboy Could this be implemented?

**Comment by johan-lejdung** [comment]
I updated to the newest version and that made it work. Although the documentation should be updated to reflect this.

**Comment by appleboy** [comment]
@johan-lejdung Can you send the PR?

**Comment by appleboy** [comment]
I will update the document.

**Comment by johan-lejdung** [comment]
Thanks!

**Comment by slimus** [comment]
fixed https://github.com/appleboy/gorush/pull/487
