### ISSUE TITLE
iOS Sound doesn't work

### ISSUE THREAD

**Issue by tosbaha** [appleboy/gorush#383]
I send the following payload but sound is not delivered. I see the notification on device but no sound ever. How can I debug this issue? Btw on iOS sound is a string according to [documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1). Why we have to define those extra values?

```json
{
  "notifications": [
    {
      "tokens": ["mytoken"],
      "platform": 1,
      "topic":"com.mytopic",
      "message": "Hello World iOS!",
       "sound": {
            "critical": 1,
            "name": "default",
            "volume": 2.0
        }
    }
  ]
}
```

I also tried gRPC interface again sound doesn't work. Here is the NodeJS code

```javascript
  var client = new services.GorushClient('localhost:9000',
    grpc.credentials.createInsecure());
  var request = new messages.NotificationRequest();
  var alert = new messages.Alert();
  request.setPlatform(1);
  request.setTokensList(["mytoken"]);
  request.setMessage("Hello!!");
  request.setTitle("hello2");
  request.setBadge(2);
  request.setCategory("mycategory");
  request.setSound("default")
  alert.setTitle("title");
  request.setAlert(alert);
  request.setTopic("com.mytopic");
  client.send(request, function (err, response) {
    if(err) {
      console.log(err);
    } else {
      console.log("Success:", response.getSuccess());
      console.log("Counts:", response.getCounts());
    }
});
```

Btw  your issue 
 [[iOS] Silent notification must not contain the alert, sound, or badge keys. #156 ](https://github.com/appleboy/gorush/issues/156) is not valid. Silent notifications CAN have sound

[Documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH10-SW8)

To support a background update notification, make sure that the payload’s aps dictionary includes the content-available key with a value of 1. **If there are user-visible updates that go along with the background update, you can set the alert, sound, or badge keys in the aps dictionary, as appropriate**. 

**PS:**
If I change source code and add `payload.Sound("default")` at the end of  `GetIOSNotification` function, I get the sound. So I guess either you are using old apns2 framework or sound extraction part of your code is wrong.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@tosbaha Do you have time to help try the latest version? Thanks.

**Comment by tosbaha** [comment]
Sound works with latest commit. Thanks.

**Comment by tosbaha** [comment]
gRPC interface still is not working though. I guess it needs update as well.

**Comment by appleboy** [comment]
@tosbaha Yes. It is not working with gRPC interface. I will take it.
