### ISSUE TITLE
threadid is not being sent in app notification for ios

### ISSUE THREAD

**Issue by andthereitgoes** [appleboy/gorush#388]
Hi @appleboy 

I am trying to send `thread-id` based on https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html

Although there is no documentation for `thread-id`, I looked at `PushNotification` in https://github.com/appleboy/gorush/blob/master/gorush/notification.go

Based on that, here's my `api/push` POST payload that is being sent to gorush push API but the app notification received on the iphone doesn't have threadID

```
{
    "notifications": [
        {
            "platform": 1,
            "message": "test message with threadid",
            "badge": 3,
            "alert": {
                "title": "New offer",
                "body": "test message with threadid"
            },
            "data": {
                "name": "John Doe",
                "id": "b48edd23-04b3-11e9-9d2d-66a036430288"
            }
	 "threadID": "b48edd23-04b3-11e9-9d2d-66a036430288"
        }
    ]
}
```

what am I doing wrong?

**Comment by appleboy** [comment]
@andthereitgoes change `"threadID"` to `"thread-id"`

**Comment by andthereitgoes** [comment]
@appleboy Thanks, that worked
