### ISSUE TITLE
Can't import "github.com/appleboy/gorush/vendor/google.golang.org/grpc" in Golang project.

### ISSUE THREAD

**Issue by gavinyangs** [appleboy/gorush#390]

**Comment by d3sire** [comment]
Yep, having the same issue. Would suggest to remove the vendoring of the grpc related functionality since it is meant to be imported.

**Comment by coip** [comment]
also impacted by this issue.

how are you guys mitigating this?

**Comment by ahmet** [comment]
Stuck at same point.

**Comment by appleboy** [comment]
@gavinyangs @d3sire @ahmet Try the latest code base. Can't reproduce this problem.
