### ISSUE TITLE
RHEL issue - bad ELF interpreter

### ISSUE THREAD

**Issue by mesibo** [appleboy/gorush#395]
Installation on RHEL results in message /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

    $ ./gorush
    bash: ./gorush: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

    $ cat /etc/redhat-release 
    CentOS Linux release 7.4.1708 (Core) 

Let me know if you need more information.

**Comment by dj95** [comment]
If you check the linked dependencies for the binary with `ldd gorush`, you will see, that the libc-musl dependency is missing on your system. 

One solution is, to install libc-musl on your system.

The other solution is to build the binary on a non libc-musl system, as the go compiler then links the non-musl libc into it.
