### ISSUE TITLE
POST /api/push  displays success but it does not give any notification in Android

### ISSUE THREAD

**Issue by harshgrovr** [appleboy/gorush#409]
I am using postman to make following request:

POST http://localhost:8088/api/stat/go

{
  "notifications": [
    {
      "tokens": ["server_key", "mobile_token"],
      "platform": 2,
      "message": "This notification will go to iOS and Android platform via Firebase!"
    }
  ]
}
What is token_a and token_b (server_key and phone_token)? I used various combination of entering those but didn't work! (I tried using both server_key and Legacy key)

But, if I am doing it with https://fcm.googleapis.com/fcm/send; using same credentials as above then I am getting notification. So that means credentials are correct.

Console Message: 

INFO[2019/05/05 - 17:59:46] | header | POST /api/push ::1 application/json PostmanRuntime/7.6.0 
[GIN] 2019/05/05 - 17:59:46 | 200 |     116.395µs |             ::1 | POST     /api/push
DEBU[2019/05/05 - 17:59:46] Start push notification for Android          
ERRO[2019/05/05 - 17:59:46] FCM server send message error: 401 error: 401 Unauthorized 

Postman message: {
    "counts": 1,
    "logs": [],
    "success": "ok"
}

can you please help?

**Comment by appleboy** [comment]
`api_key` is your fcm server key.

```json
{
  "notifications": [
    {
      "api_key": "your fcm key",
      "tokens": ["mobile_token_A", "mobile_token_B"],
      "platform": 2,
      "message": "This notification will go to iOS and Android platform via Firebase!"
    }
  ]
}
```

**Comment by harshgrovr** [comment]
where do i specify it in request?

**Comment by harshgrovr** [comment]
It worked!

Please update Read me file, the api_key option is missing there in the request.

Thanks for the prompt response!

**Comment by appleboy** [comment]
@harshgrovr 

See the request body: https://github.com/appleboy/gorush#request-body

**Comment by harshgrovr** [comment]
thanks!
