### ISSUE TITLE
Go modules issue with gofight dependency

### ISSUE THREAD

**Issue by jhernandezb** [appleboy/gorush#415]
There is an issue introduced by the `gofight` dependency 

`gofight` has been updated to use go modules and import path 'v2'  but this repo relies on using
`gopkg.in/appleboy/gofight.v2` as import path 

But now `gopkg.in/appleboy/gofight.v2` redirects to v2.1.1 which is the version with go modules and import path v2.
This creates a conflict  it requires you to switch to `github.com/appleboy/gofight/v2` in all imported paths.
 
```sh
go: gopkg.in/appleboy/gofight.v2@v2.0.0: go.mod 
has non-....v2 module path "github.com/appleboy/gofight/v2" at revision v2.0.0
```

I've tested this change on my fork.

go.mod
`github.com/appleboy/gofight v2.0.0+incompatible` => `github.com/appleboy/gofight/v2 v2.1.1`

server_test.go
`gofight "github.com/appleboy/gofight/v2"`

**Comment by medcampus** [comment]
How to solve this?

**Comment by appleboy** [comment]
@medcampus Please show more detail about your question.

**Comment by jhernandezb** [comment]
@medcampus  I had to do `go get github.com/appleboy@master` because the last tagged release `v1.11.1` doesn't contain the fix, so probably a new version release would fix it as well.

**Comment by appleboy** [comment]
@jhernandezb I will release a new version asap.

**Comment by appleboy** [comment]
bump to v1.11.2 https://github.com/appleboy/gorush/releases/tag/v1.11.2
