### ISSUE TITLE
Sync mode and client timeouts issue

### ISSUE THREAD

**Issue by HelmiRifai** [appleboy/gorush#422]
All our clients are sending notifications in sync mode, but from my understanding of the code sync is still using the internal "queue" to send out the notification with the addition of the waitgroup to notify the client of the resulting status.

Our issue is that under high load and with a client timeout of 60-120s we see increase in internal queues and if the notification remains in the queue for 120+ seconds the client will timeout; then the notification could still be sent to the device. This is a rarer case ( estimated at 1%) and we have worked around it mainly by backoff on the workers and scaling of the gorush deployment.

Let me know if this makes sense based on the code and if you point me to what can be modified to handle a client timeout ( or disconnect) better I would be happy to work on it.

**Comment by HelmiRifai** [comment]
@appleboy appreciate any input and willing to work on a solution for this

**Comment by appleboy** [comment]
@HelmiRifai The notification will not be sent after the client disconnected `Gorush` server if the notification in the queue list. I will send the PR to implement the feature.
