### ISSUE TITLE
Support iOS 13 apns-push-type

### ISSUE THREAD

**Issue by McPo** [appleboy/gorush#423]
`apns-push-type` is now a required key in the payload starting from iOS 13, without this notifications can be delayed or dropped altogether.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc

**Comment by maksymkotov** [comment]
Just tested push on iOS 13. So far, it works.

**Comment by McPo** [comment]
It was raised as an (actual) issue by one of our iOS Developers. I have since tested it myself, and it does appear to work fine. However there might be some cases where it doesn't. I'll get more info and update this issue.

A quick "fix" is to upgrade APNS2 from v0.16.0 to v0.19.0 (Theres very minor differences, so should be fine). It now adds "alert" as the default apns-push-type. https://github.com/sideshow/apns2/blob/da20148a3e9233a832525974f8fe3312325a9a50/client.go#L214

However gorush should ideally propagate the PushType setting

**Comment by McPo** [comment]
Added a PR #424

**Comment by appleboy** [comment]
closed via #424
