### ISSUE TITLE
Any plan to support HMS Push kit, Huawei push notifications 

### ISSUE THREAD

**Issue by abdulnewswav** [appleboy/gorush#426]
Hi

As you know all, New Huawei devices don't support Google Play services, that means FCM won't work on it, so Huawei build their own SDK to send push notifications to these new devices like Mate30
https://developer.huawei.com/consumer/en/service/hms/developer.html

**Comment by appleboy** [comment]
@abdulnewswav I don't have any Huawei device but maybe I can't implement the first version for HMS

**Comment by winwisely99** [comment]
Now that Huawei have started to deploy devices, i wonder if any stargazers have devices now ?

Would be awesome to try to get this going.

**Comment by msalihkarakasli** [comment]
Hi @appleboy, I can support testing and implementation processes for this feature. Let's add 3rd platform as Android - HMS. I don't know go language very well but I can provide information about Huawei Push system.

**Comment by De-Luxis** [comment]
We also have plans to port the application to their platform and there was a question with their push notifications.
Let's take part in the tests.

**Comment by appleboy** [comment]
@De-Luxis @msalihkarakasli I merged the PR. Thanks for @msalihkarakasli contribution.
