### ISSUE TITLE
go get github.com/appleboy/gorush

### ISSUE THREAD

**Issue by medcampus** [appleboy/gorush#428]
go: github.com/appleboy/gofight@v2.0.0+incompatible: go.mod has post-v2 module path "github.com/appleboy/gofight/v2" at revision v2.0.0
go: gopkg.in/appleboy/gofight.v2@v2.0.0: go.mod has non-....v2 module path "github.com/appleboy/gofight/v2" at revision v2.0.0
go: error loading module requirements

**Comment by appleboy** [comment]
Please use the go `v1.11` up version and enable the go module.

```sh
export GO111MODULE=on
go get github.com/appleboy/gorush
```
