### ISSUE TITLE
Cannot build for aws lambda 

### ISSUE THREAD

**Issue by conradludgate** [appleboy/gorush#432]
I ran the commands as listed in the README,
```sh
git clone https://github.com/appleboy/gorush.git
cd gorush && make build_linux_lambda
```

But I get the following error

```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags 'lambda' -ldflags '-s -w -X 'main.Version=v1.11.2-7-ga49bf91'' -o release/linux/lambda/gorush
# github.com/appleboy/gorush/gorush
gorush/server_lambda.go:10:6: RunHTTPServer redeclared in this block
	previous declaration at gorush/server.go:144:27
make: *** [build_linux_lambda] Error 2
```

I'm not sure what the intent is, whether it's to only build a certain subset of files, but it's clearly not doing that in this case.

I am using go1.12.7 on macOS 10.15 if that helps

**Comment by appleboy** [comment]
@conradludgate Please try the latest version. Thanks for your reminder.

**Comment by conradludgate** [comment]
Seems to be fixed. Thanks!
