### ISSUE TITLE
Silent notifications not working on iOS?

### ISSUE THREAD

**Issue by thesauravmitra** [appleboy/gorush#438]
Hi, I've recently switched to using `gorush` to deliver notifications to my app.

I am checking if my app is receiving notifications (in my case, while the app is in the foreground) by implementing the following in `AppDelegate.swift`:

```swift
func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
    print("USER INFO", userInfo)
    completionHandler(.noData)
}
```

If I don't set the delegate function `userNotificationCenter(_, willPresent: withCompletionHandler:)`, then all remote notifications will be processed in the `AppDelegate` function.

If I send the following data, the function is not called, implying that the notification was not received:
```
{
    "notifications": [
        {
            "tokens": ["my_token"],
            "data": {"custom_data_field": 3},
            "platform": 1,
            "topic": "my_topic",
            "development": true, 
            "content_available": true
        }
    ]
}
```

If I add a `title: "my_title"` to the notification, with or without the `content_available` field, the function is called, which means the notification has most definitely been received.

This seems to imply that silent notifications are not being delivered correctly. Any ideas?

**Comment by slimus** [comment]
@thesauravmitra 
Why do you think that silent notifications are not being delivered correctly?
I read this article https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app and it seems all is ok

**Comment by slimus** [comment]
@appleboy close this issue?
