### ISSUE TITLE
Does the gorush support graceful shutdown?

### ISSUE THREAD

**Issue by emiksk** [appleboy/gorush#441]
Does the gorush support 'graceful shutdown' ?
The 'graceful shutdown' I say means that notifications workers and queue have are sent to APNs/FCM before a push notification service is shutdown.
I have an option to use sync mode, but I use async mode if possible.

If the gorush doesn't support 'graceful shutdown', I would like to try to contribute your project.

Thank you.

**Comment by appleboy** [comment]
Not yet, I will add this feature asap.

**Comment by emiksk** [comment]
Thank you for your response.

That's good news for me. :)

**Comment by appleboy** [comment]
I am working on this feature.
