### ISSUE TITLE
grpc call send panic

### ISSUE THREAD

**Issue by zhaoqb** [appleboy/gorush#446]
gorush/worker.go    

```go
// SendNotification is send message to iOS or Android
func SendNotification(req PushNotification) {
	if PushConf.Core.Sync {
		defer req.WaitDone()
	}

	select {
	case <-req.ctx.Done():
	default:
		switch req.Platform {
		case PlatFormIos:
			PushToIOS(req)
		case PlatFormAndroid:
			PushToAndroid(req)
		}
	}
}
```

**Comment by appleboy** [comment]
@zhaoqb Thanks for your report. I will take it.

**Comment by appleboy** [comment]
Side effect from https://github.com/appleboy/gorush/pull/431

**Comment by cfanboy** [comment]
I run the gorush server by downloaded binary and the gRPC example codes, but panic:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x18b892f]

goroutine 72 [running]:
github.com/appleboy/gorush/gorush.SendNotification(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000f4a40, 0x1, 0x1, 0x1, ...)
        /Users/xxx/golang/src/github.com/appleboy/gorush/gorush/worker.go:25 +0x4f
created by github.com/appleboy/gorush/rpc.(*Server).Send
        /Users/xxx/golang/src/github.com/appleboy/gorush/rpc/server.go:92 +0x4b8

**Comment by tsauzeau** [comment]
Hey, any news on that ?

**Comment by slimus** [comment]
fixed https://github.com/appleboy/gorush/pull/484/files

**Comment by appleboy** [comment]
@slimus Thanks for your PR.
