### ISSUE TITLE
Question: can this library be used as to import in a personal project?

### ISSUE THREAD

**Issue by kogisin** [appleboy/gorush#448]
## Steps that I have done before I ask this question

- I've successfully built `gorush` binary file and sent push notification to my android phone.

- I've also successfully sent push notification using `POST /api/push` web API. 
To accomplish this, I git cloned this project and created `config.toml` inside [gorush](https://github.com/appleboy/gorush/tree/master/gorush) folder and changed some params into my own.

## What I am trying to accomplish

However, what I am trying to accomplish here is to import this library in my own web server project and build custom push notification `web APIs`. 

Iis it standalone?

If it is plausible to accomplish, I will be appreciated if you could provide some resources or examples I can take a reference to because I can't seem to find it anywhere in this project.

**Comment by slimus** [comment]
Hi @kogisin ! This is standalone server, not a library. 
In your case, you can:
1. Use your server for store mobile tokens in db and use gorush only as transportation layer
2. Use your server for store tokens and write code for send pushes using [FCM](github.com/appleboy/go-fcm) and [APNS](github.com/sideshow/apns2) libraries

**Comment by kogisin** [comment]
@slimus That's fair enough. Thanks. I will close the issue.
