### ISSUE TITLE
Failed pushes never dispatch to the hook URL

### ISSUE THREAD

**Issue by Pantani** [appleboy/gorush#449]
Hey, I did have some failed push notifications:

```
time="2019/12/21 - 02:40:12" level=error msg="| failed-push | android [**********Y:xxxxxxxxxx.....**********] | <MESSAGE> | Error Message: unregistered device"
```

And I did set the env vars `GORUSH_CORE_SYNC` as false and the `GORUSH_CORE_FEEDBACK_HOOK_URL` with the API hook URL, but the failed event is never dispatched to my hook API. Do I need to configure another stuff?

**Comment by vikmeup** [comment]
@appleboy

**Comment by appleboy** [comment]
I will take it.

**Comment by Pantani** [comment]
@appleboy, any update?

**Comment by appleboy** [comment]
@Pantani Sorry for the delayed response. I will reproduce the problem today or tomorrow.

**Comment by slimus** [comment]
Hi @Pantani. I tried to reproduce your problem but I can't. All failed push sended. Did you receive any post request to your hook url? Please tell me are your backend for hooks working correctly? 
@appleboy I think need to add timeout to DispatchFeedback -> httpclient (may be configurable). What do you think?

**Comment by appleboy** [comment]
> @appleboy I think need to add timeout to DispatchFeedback -> httpclient (may be configurable). What do you think?

@slimus Good catch. I will add a timeout setting for the webhook.

**Comment by appleboy** [comment]
@slimus I created new PR: https://github.com/appleboy/gorush/pull/473

**Comment by slimus** [comment]
@Pantani can you please test it again in latest master?

**Comment by Pantani** [comment]
@vikmeup can you test please?

**Comment by slimus** [comment]
@Pantani @vikmeup any news here?

**Comment by yaronius** [comment]
I am actively using feedback hook and everything works just fine 🤷‍♂️

**Comment by slimus** [comment]
@appleboy close this issue?

**Comment by appleboy** [comment]
@yaronius @slimus Thanks for your feedback.
