### ISSUE TITLE
Proxy interferes with healthcheck

### ISSUE THREAD

**Issue by McPo** [appleboy/gorush#456]
If you set the proxy via the config file `http_proxy:`, the docker healthcheck `gorush --ping` attempts to use the proxy. Which results in localhost (used by the healthcheck) resolving to the proxy as opposed to the container.

```
received request to: GET localhost:8088/healthz
Error: connect ECONNREFUSED 127.0.0.1:8088
```

Ive worked around this issue by using `HTTP_PROXY` env variables. (In my case this is actually preferred). You could also disable the healthcheck as a temp workaround.

A proper fix to this issue would be to have `gorush --ping` implicitly ignore the proxy, or have it explicit `gorush --no-proxy --ping`

**Comment by appleboy** [comment]
@McPo I will take it and we don't need to set any proxy in `gorush --ping` command.
