### ISSUE TITLE
Firebase broken on latest master

### ISSUE THREAD

**Issue by m1schka** [appleboy/gorush#458]
Hey,

when working with the latest master docker container server, the FCM appears to be broken. IOS seems fine but on Android, the notification arrives but the notification in there is null (`RemoteMessage.GetNotification()`).

logs from the server:

```
time="2020/01/28 - 08:21:31" level=debug msg="Android Success count: 1, Failure count: 0"
time="2020/01/28 - 08:21:31" level=info msg="| succeeded-push | android [**********0:APA91bGu***AtYzx0nYxBir8DZ**********] foobar123"
```

rolling back to 1.11.2 fixes it

I know working with master is always dangerous but just letting you know. :)

**Comment by appleboy** [comment]
@m1schka Thanks. I will try it on the master branch.

**Comment by appleboy** [comment]
Anybody can help to try the bugs in the master branch?

**Comment by slimus** [comment]
@appleboy yes, it's true. Problem line is here https://github.com/appleboy/gorush/blob/master/gorush/notification_fcm.go#L65

**Comment by slimus** [comment]
@appleboy please look at my PR

**Comment by appleboy** [comment]
OK. I will take it.

**Comment by appleboy** [comment]
@m1schka Can you help to try the latest version? Thanks.
