### ISSUE TITLE
Question: env variables to replace config file options?

### ISSUE THREAD

**Issue by setevoy2** [appleboy/gorush#467]
Can't find anything about using environment variables for the Gorush - is it possible to use some to replace values from the config.yml to avoid updating that file each time?

**Comment by slimus** [comment]
Yes, you can use env for config. 
The code is here: https://github.com/appleboy/gorush/blob/master/config/config.go#L223
And example config here: https://github.com/appleboy/gorush/blob/master/k8s/gorush-deployment.yaml#L27
