### ISSUE TITLE
GRPC Notification message ImageTag

### ISSUE THREAD

**Issue by medcampus** [appleboy/gorush#472]
message NotificationRequest {
  repeated string tokens = 1;
  int32 platform = 2;
  string message = 3;
  string title = 4;
  string topic = 5;
  string key = 6;
  int32 badge = 7;
  string category = 8;
  Alert alert = 9;
  string sound = 10;
  bool contentAvailable = 11;
  string threadID = 12;
  bool mutableContent = 13;
  google.protobuf.Struct data = 14;
}

**Comment by appleboy** [comment]
duplicated of #471
