### ISSUE TITLE
Can't send notification with gRPC.

### ISSUE THREAD

**Issue by oybekmuzropov** [appleboy/gorush#476]
Hello. I can't send notification by gRPC. I run gRPC server with GORUSH_GRPC_ENABLED=true GORUSH_GRPC_PORT=9000 gorush. Log is "INFO[2020/02/27 - 11:56:44] gRPC server is running on 9000 port". I used this code. 
       conn, err := grpc.Dial(address, grpc.WithInsecure())
	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	c := proto.NewGorushClient(conn)

	tokens := []string{"token1"}

	r, err := c.Send(context.Background(), &proto.NotificationRequest{
		Platform: 2,
		Tokens: tokens,
		Title: "Test",
		Message:  "test message",
		Key:"API Key",
	})

	if err != nil {
		log.Fatalf("could not greet: %v", err)
	}

	log.Printf("Success: %t\n", r.Success)
	log.Printf("Count: %d\n", r.Counts).
But message did not send. Error is "2020/02/27 12:51:18 could not greet: rpc error: code = Unavailable desc = connection closed". I try to connect gRPC server by evans. But I did't do.

**Comment by aureliensibiril** [comment]
Using appleboy/gorush:lastest docker image.

Same here 
```
14 UNAVAILABLE: Trying to connect an http1.x server"
```

**Comment by oybekmuzropov** [comment]
@aureliensibiril I run gorush with docker image. But gRPC did not work.

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Please try the latest version.
