### ISSUE TITLE
Client does not get all notifications.

### ISSUE THREAD

**Issue by oybekmuzropov** [appleboy/gorush#480]
When Client was offline, I sent 10 notifications to client. In this case, client only got the latest notification which I sent. What I do for client get all notifications .

**Comment by slimus** [comment]
@oybekmuzropov which platform?

**Comment by oybekmuzropov** [comment]
@slimus Android

**Comment by slimus** [comment]
@oybekmuzropov I think it is client problem . Please show me your android source code

**Comment by oybekmuzropov** [comment]
@slimus I understood. Thank you!!!

**Comment by slimus** [comment]
@oybekmuzropov can we close this issue?
