### ISSUE TITLE
Error Message: invalid registration token

### ISSUE THREAD

**Issue by NurRozikin** [appleboy/gorush#486]
gorush -android --title "MyTitle" -m "Hi" -k AIzaSyBcLEgcAmI6ksXqx9ReXXXXXXXXX -t U2p2wKrqLsHjLn1es0zudXqOCL1fOGEZIQlhF3KARWKyOCZi3jB2crinEPYVJztjtGxbMn6cIUJck3WH2EgVSg8SZGf_AkXXXXXXXXXXX

I always get error message below :

time="2020/03/14 - 00:06:49" level=debug msg="Start push notification for Android"
time="2020/03/14 - 00:06:50" level=debug msg="Android Success count: 0, Failure count: 1"
time="2020/03/14 - 00:06:50" level=error msg="|\x1b[97;41m failed-push \x1b[0m| \x1b[97;43mandroid\x1b[0m [**********HjLn1es7NDCK0zudXqOCL1fOGEZIQlhFWKyOCZi3jB2crinEPYVJztjtGxbMn6cIUJck3WH2EgVSg8SZGf_AkwufFeYYzVVC4RQ48dFqy**********] | Hi | Error Message: invalid registration token"

What should I do ? I already set apikey from Legacy server key.

**Comment by slimus** [comment]
Please check your ApiKey. This error returns from FCM server

**Comment by NurRozikin** [comment]
OK, I will close this issue due to wrong Device Token
