### ISSUE TITLE
Not able to use gorush

### ISSUE THREAD

**Issue by anandhkumar** [appleboy/gorush#489]
I have install gorush in my linux system
OS: Centos 7
Go version :1.12.5

mkdir $HOME/src
cd $HOME/src
git clone https://github.com/appleboy/gorush.git
cd gorush
go install

After follow the above steps try to run the command getting below error

$ gorush
-bash: gorush: command not found

Then I try to run go using command "go run main.go". Now the server started. When I hit the curl command not seeing any response

curl -X POST -H "Content-Type: application/json" -d '{"notifications": [{"tokens": ["token_a", "token_b"],"platform": 2,"message": "Hello World Android!"}]}' http://127.0.0.1:8088/api/push/
Also not seeing any curl response in log file.

any body help me here please

**Comment by slimus** [comment]
Hi @anandhkumar !
Please read about how to install go from tar: https://golang.org/doc/install#install. Did you make `export PATH=$PATH:/usr/local/go/bin` (where /usr/local/go/bin is your path where golang was installed)? Show me your PATH variable
Also show me log after you run `go run main.go` and show me your config or env (without platforms tokens)

**Comment by appleboy** [comment]
@anandhkumar Add `$GOPATH/bin` in `PATH` env.

**Comment by slimus** [comment]
@anandhkumar @appleboy close this issue?
