### ISSUE TITLE
[Question] How to register clients?

### ISSUE THREAD

**Issue by pwFoo** [appleboy/gorush#490]
Hi,
I'm searching for a self hosted push notification service to separate push service from my web application.

I played with the web-push-php library server side and a javascript client part.

Client need to register und send information the the server. Server need to store that information to send push notifications to the clients via mozilla / microsoft / google push service.

I deployed gorush with docker, but how to use it to register and send push notifications to clients? Is there an example available about the needed steps?

**Comment by slimus** [comment]
Hi pwFoo, 

You should to store users and their tokens in your DB and use gorush only to send push to your clients.
So gorush is only transport (with error checking, retry policy and webhooks) for your push messages.

**Comment by pwFoo** [comment]
But what's about vapid pub / priv key?
https://github.com/SherClockHolmes/webpush-go

I know about because of webpush-php tests. I needed vapid key to send notifications via push provider to the client? Vapid keys should be gorush or application part and how to set for the push notification?

**Comment by slimus** [comment]
webpush is not supported yet, sorry. Please move discussion about webpush to #248

**Comment by pwFoo** [comment]
Ok, thanks
