### ISSUE TITLE
Endpoint /api/config?

### ISSUE THREAD

**Issue by pwFoo** [appleboy/gorush#491]
Hi @appleboy,
the config file could contains data like cert / key. So api endpoint /api/config should be disabled in production environment?

**Comment by slimus** [comment]
Hi @pwFoo ,
I think you can change `api.config_uri` to smthng like `/secure-api/config/<uuid>` and restart gorush.
Gorush has stat_go_uri, stat_app_uri, sys_stat_uri, metric_uri  and we should disable (or secure: add some hash or add http basic auth) it also.

**Comment by pwFoo** [comment]
Ok, some possible solutions with basicauth, block path or use a additional hash. Thanks
