### ISSUE TITLE
Add Priority tag in grpc notification request

### ISSUE THREAD

**Issue by medcampus** [appleboy/gorush#492]
message NotificationRequest {
  repeated string tokens = 1;
  int32 platform = 2;
  string message = 3;
  string title = 4;
  string topic = 5;
  string key = 6;
  int32 badge = 7;
  string category = 8;
  Alert alert = 9;
  string sound = 10;
  bool contentAvailable = 11;
  string threadID = 12;
  bool mutableContent = 13;
  google.protobuf.Struct data = 14;
  string image = 15;
}

**Comment by medcampus** [comment]
Any updates

**Comment by appleboy** [comment]
See the PR #494
