### ISSUE TITLE
Fix test(s)

### ISSUE THREAD

**Issue by slimus** [appleboy/gorush#495]
https://cloud.drone.io/appleboy/gorush/306/1/8

**Comment by appleboy** [comment]
@slimus I will fix the testing this week.

**Comment by slimus** [comment]
@appleboy any news here?

**Comment by appleboy** [comment]
I will update the secret to fixing unit testing.

**Comment by appleboy** [comment]
@slimus Done.

**Comment by slimus** [comment]
@appleboy  thanks!
