### ISSUE TITLE
Can't send iOS notification with p8 in command line?

### ISSUE THREAD

**Issue by internalG** [appleboy/gorush#510]
always got error of "Error Message: MissingProviderToken". No way to test p8 in command line?

**Comment by appleboy** [comment]
Please show your command.

**Comment by internalG** [comment]
./gorush -ios -m "{ \"aps\": {\"alert\": \"Test\", \"sound\": \"default\" }}" \
  -i "AuthKey_ABC.p8" \
  -t "ONETOKEN" \
  -production

**Comment by slimus** [comment]
@internalG can you please show you logs?

**Comment by internalG** [comment]
./gorush -ios -m "{ \"aps\": {\"alert\": \"Test\", \"sound\": \"default\" }}" \
>   -i "AuthKey_***.p8" \
>   -t "0a19***" \
>   -production
INFO[2020/05/17 - 22:01:55] Init App Status Engine as memory             
DEBU[2020/05/17 - 22:01:55] Start push notification for iOS              
ERRO[2020/05/17 - 22:01:57] | failed-push | ios [**********fa36f22**********] | { "aps": {"alert": "Test", "sound": "default" }} | Error Message: MissingProviderToken

**Comment by internalG** [comment]
I can use web api to send to apns now. It seems there's no option to pass key_id and team_id in command line, so that's why p8 sending failed.

**Comment by slimus** [comment]
@internalG please look at #511

**Comment by internalG** [comment]
Thank you all. I'll try in next release.
