### ISSUE TITLE
Android configuration for getting notification 

### ISSUE THREAD

**Issue by mehdirouhandeh** [appleboy/gorush#529]
Hi,
I'm an Android developer and want to know how can I configure our app to receive notification from Gorush.

**Comment by appleboy** [comment]
You can see the document: https://firebase.google.com/docs/cloud-messaging/android/client

**Comment by mehdirouhandeh** [comment]
@appleboy thank you for your help

**Comment by mehdirouhandeh** [comment]
@appleboy Thak you for your help
