### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yxb-git** [appleboy/gorush#530]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc7332e]

goroutine 49839 [running]:
github.com/appleboy/gorush/gorush.PushToIOS.func1(0xc0144af700, 0xc0001210e0, 0xc00895a840, 0xc0144d97e0, 0xc0144cbd0c, 0xc0144cbd20, 0xc00890e980, 0x40)
	/drone/src/gorush/notification_apns.go:418 +0x17e
created by github.com/appleboy/gorush/gorush.PushToIOS
	/drone/src/gorush/notification_apns.go:389 +0x1fb

**Comment by skorobkov** [comment]
I believe problem is in returned value from Push function
https://github.com/appleboy/gorush/blob/master/gorush/notification_apns.go#L393
res is nil when there is some problem in apns connection

**Comment by appleboy** [comment]
@skorobkov @yxb-git I will take it.
