### ISSUE TITLE
Probleme with "max capacity reached" on latest release?

### ISSUE THREAD

**Issue by AmarOk1412** [appleboy/gorush#535]
Hi,
On some servers I use gorush 1.12 and tried to update with last binaries. However, very soon I got some errors like "max capacity reached". Am I the only one experiencing this?
Can't really provide more logs from now, as I use the 1.12 version for now

**Comment by appleboy** [comment]
@AmarOk1412 Please increase the number of `queue_num` or set as `zero` for unlimited in YAML config.

**Comment by sankethkini** [comment]
@appleboy I have tried making queue_num as ```zero``` but it is taking it as ```8192```  and the issue ```max capacity reached``` still persists. What further steps can we take to avoid this issue. Please help to close this issue ASAP.

**Comment by appleboy** [comment]
@sankethkini you can try another solution like Redis, NSQ, or Nats as queuing system. Please try the v1.15 version.

https://github.com/appleboy/gorush/blob/7f4a6670a9822e7f326c622e77a68585abdee8f1/config/config.go#L65-L79

https://github.com/appleboy/gorush/releases/tag/v1.15.0

**Comment by sankethkini** [comment]
We are trying to use ```redis``` for queue. For that we used following configs
1. queue.engine: redis
2. queue.redis.addr: host:6379

We are not able to see if `queue` related changes are applied by hitting /api/config.  Also redis as queue is not applied as we have checked it by restarting pod.
using version : 1.13
