### ISSUE TITLE
Not working IOS push notifications when failed push

### ISSUE THREAD

**Issue by mayken** [appleboy/gorush#536]
When sending a push notification to IOS, the request hangs and there is no response, it does not write logs and does not help in sync: true. In v1.11.2 release it is OK!

**Comment by JS1010111** [comment]
Same here on 1.13.0. Docker Docker version 19.03.12.

iOS notifications seems to be in the queue forever.

Downgraded back to 1.11.2 and it's working fine again.

**Comment by jeromepasvantis** [comment]
Hey, I'm running into the same (or similar?) issues with v1.13.0 - also on Docker. It just hangs forever without `failed-push` or `succeeded-push` logs:

`{"level":"debug","msg":"Start push notification for iOS","time":"2020-11-10T10:17:25Z"}`

Using v1.11.2 and v.1.12.0 and with the same payload, I receive the notifications nicely. :)

**Comment by yokotaso** [comment]
@jeromepasvantis @JS1010111 @mayken 
I run into a same issue. Perhaps, would you have value `ios.max_concurrent_pushes` in config.yaml ?

https://github.com/appleboy/gorush/blob/master/config/config.go#L334

I run gorush config without `ios.max_concurrent_pushes`. I confirmed like below:

```
curl localhost:8088/api/config
...
ios:
  max_concurrent_pushes: 0
```

And I send APNs push via gorush, gorush would be hungup.
With set positive integer in `ios.max_concurrent_pushes`, gorush work fine.

**Comment by tomquas** [comment]
thx @yokotaso, setting max_concurrent_pushes fixed it for me, too

**Comment by SpaWn2KiLl** [comment]
thanks @yokotaso , fixed it for me also 👍

**Comment by JS1010111** [comment]
Thanks @yokotaso! Works for me with `ios.max_concurrent_pushes`.

**Comment by SebastienMelki** [comment]
> max_concurrent_pushes

THANK YOU

**Comment by SebastienMelki** [comment]
> @jeromepasvantis @JS1010111 @mayken
> I run into a same issue. Perhaps, would you have value `ios.max_concurrent_pushes` in config.yaml ?
> 
> https://github.com/appleboy/gorush/blob/master/config/config.go#L334
> 
> I run gorush config without `ios.max_concurrent_pushes`. I confirmed like below:
> 
> ```
> curl localhost:8088/api/config
> ...
> ios:
>   max_concurrent_pushes: 0
> ```
> 
> And I send APNs push via gorush, gorush would be hungup.
> With set positive integer in `ios.max_concurrent_pushes`, gorush work fine.

THANK YOU

**Comment by appleboy** [comment]
I add `100` as default value of `max_concurrent_pushes`.
