### ISSUE TITLE
Migrate from legacy FCM HTTP API to HTTP v1 API

### ISSUE THREAD

**Issue by ghost** [appleboy/gorush#550]
This project's dependency `github.com/appleboy/go-fcm ` uses legacy FCM HTTP API. 
Are there any plans to migrate it to the v1 API as [recommended](https://firebase.google.com/docs/cloud-messaging/migrate-v1) by Firebase documentation? Or maybe 
integrate Firebase Admin SDK instead of using raw HTTP API. 

Also, how can I pass `TitleLocArgs `and` BodyLocArgs` values as array of strings? In the dependency mentioned above
these values are defined as plain strings whereas [FCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref) specifies them as array of strings .
When I make a request with `TitleLocArgs` I get an error `Error Message: unknown error type`. However when I make same request connecting directly to FCM server everything works fine.

**Comment by giovanni-orciuolo** [comment]
+1

**Comment by cdivita** [comment]
+1 also for me

**Comment by IlyaGulya** [comment]
Hello!
Today Google announced that FCM Legacy HTTP API will be removed on June 20, 2024.
I think now this ticket should get a bit more attention 🙂

**Comment by appleboy** [comment]
@IlyaGulya I will take it.

**Comment by pvincendeau** [comment]
> @IlyaGulya I will take it.
Hello @appleboy.
Do you have any idea of a time schedule for the release of a new version using FCM HTTP v1 API instead of the legacy one please ?
Thanks a lot in advance !

**Comment by c0olix** [comment]
Hey there, I found your promising notification service yesterday. I would really love to use this, but this issue is keeping me from using it. Any chance to get an estimation, when Firebase Cloud Messaging API (V1) is implemented?

Thanks

**Comment by c0olix** [comment]
Bump

**Comment by sankethkini** [comment]
> @IlyaGulya I will take it.

@appleboy any estimation on by when this will get implemented?

**Comment by appleboy** [comment]
Hey, sorry about that. I'm planning to kick off the API transition this month, and hopefully, by next month, there'll be a version ready for everyone to test out.

**Comment by obuzyig** [comment]
Dear @appleboy,

Thank you for your amazing effort.

I have checked out potential authorization methods on FCM HTTP v1 API Documentation and wondered if it is possible to maintain the multi-tenancy on the new approach.

Regarding the previous API, the "api_key" input helps to send notifications to multiple applications. Selecting different "JSON" files, including project-id values, to authorize could be a valuable capability for somehow maintaining multi-tenancy.

**Comment by appleboy** [comment]
@obuzyig 

Thank you for reaching out and for your kind words regarding our efforts.

I'm delighted to inform you that we are fully committed to supporting multi-tenancy on the FCM HTTP v1 API platform. Your feedback regarding the potential authorization methods and the importance of maintaining multi-tenancy is greatly appreciated.

**Comment by sankethkini** [comment]
https://github.com/appleboy/gorush/issues/550#issuecomment-1997538191

@obuzyig I am aware of only one feasible method for authorization i.e, using service-account.json files. Are you aware of any other methods as such?

**Comment by obuzyig** [comment]
> [#550 (comment)](https://github.com/appleboy/gorush/issues/550#issuecomment-1997538191)
> 
> @obuzyig I am aware of only one feasible method for authorization i.e, using service-account.json files. Are you aware of any other methods as such?

@sankethkini I think FCM provides the Application Default Credentials option for applications that work on a Google-related platform or infrastructure. I do not have any other generic solutions for covering other applications.

**Comment by petenickless** [comment]
> Hey, sorry about that. I'm planning to kick off the API transition this month, and hopefully, by next month, there'll be a version ready for everyone to test out.

Hey @appleboy - just wondering if it's possible to get an update on progress with this.  Do you think the upgrade will be ready to be used in production before the legacy HTTP API is switched off in June?  

Thanks in advance 👍

**Comment by hilariocoelho** [comment]
> Hey, sorry about that. I'm planning to kick off the API transition this month, and hopefully, by next month, there'll be a version ready for everyone to test out.

Hello @appleboy . Are there any news regarding this subject?

**Comment by appleboy** [comment]
@hilariocoelho 

I am continuing with the development and expect to have a release ready for testing by everyone on `05/10` Taiwan time. Sorry for the late reply.

**Comment by appleboy** [comment]
Hi All,

**Update on current status**:

I'm currently trying to resolve the upgrade issue at https://github.com/appleboy/go-fcm/issues/38. Once the package resolves this, I will proceed with the upgrade here. I apologize for the delay in scheduling, and I will keep everyone posted on the progress here."

**Comment by appleboy** [comment]
Hi All,

**Update on current status:**

I already update the dependency package `go-fcm`. Next, I plan to update the Gorush. Maybe next week I can offer the new testing version.

https://github.com/appleboy/go-fcm/issues/38#issuecomment-2121660454

**Comment by pvincendeau** [comment]
Hello @appleboy 

Do you have any estimation on when a final release of gorush implementing the new FCM integration will be available ? The legacy API will be discontinued in less than 3 weeks and we need to know if we have to adjust our plans and look for an alternative or stick with your great solution.

Thanks in advance

**Comment by appleboy** [comment]
@pvincendeau I will release the new version this week.

**Comment by pvincendeau** [comment]
Hi @appleboy 
Do you have any news on the final release date ? I was hoping that the version will be available today as you told me ealier that it would be available this week. Our application relies on gorush to send push notification and it is one of our major feature. We really need to update as soon as possible and the deadline is now les than two weeks away.
Thanks in advance

**Comment by appleboy** [comment]
@petenickless Can you give the two days? I will release the first version on Sunday (06/09 UTC+8:00).

**Comment by appleboy** [comment]
@petenickless @IlyaGulya @hilariocoelho @cdivita I released the v1.18.0 version. Please help to try it out. https://github.com/appleboy/gorush/releases/tag/v1.18.0

**Comment by appleboy** [comment]
Please feel free to open a new issue if anyone has any further questions.

**Comment by petenickless** [comment]
Looking good our end @appleboy, thanks so much for all your hard work on this one.

**Comment by pvincendeau** [comment]
@appleboy Thank tou very much ! Everything seems to be OK on our side too. Great job !

**Comment by obuzyig** [comment]
Thank you for the amazing job @appleboy.

Is there anybody tried to address a different json file for a different application via giving it as an input in the payload? I could not find an example yet, maybe is it something like using "fcm_key_path" input?

**Comment by appleboy** [comment]
@obuzyig 

Currently, multiple FCM JSON files are not supported. This will be officially supported later.

Please create a new issue if you encounter any other problems.

**Comment by hilariocoelho** [comment]
Hello @appleboy 

Faced some breaking changes while sending push notifications using FCM but fixed everything on my side.

Still faced an old issue on HMS that led to me creating these PRs: https://github.com/karakasli/go-hms-push/pull/4 and https://github.com/appleboy/gorush/pull/645

Now that you forked the go-hms-push library you didn't include my changes so it reverted the behavior to the old buggy one.

Created [this PR](https://github.com/appleboy/go-hms-push/pull/1) again to fix the issue

**Comment by appleboy** [comment]
@hilariocoelho Please try the https://github.com/appleboy/gorush/releases/tag/v1.18.2 version.
