### ISSUE TITLE
shove vs gorush?

### ISSUE THREAD

**Issue by rrjanbiah** [appleboy/gorush#552]
Related: https://github.com/pennersr/shove/issues/3

Are there any comparison with shove? (Apart from shove offering Telegram support?)

**Comment by appleboy** [comment]
I see the main difference is the queue system in `shove`. Gorush doesn't support any queue service.

**Comment by rrjanbiah** [comment]
@appleboy Thank you!

**Comment by skorobkov** [comment]
Gorush supports HMS (Huawei Mobile Services)

**Comment by rrjanbiah** [comment]
@skorobkov Thank you!
