### ISSUE TITLE
APNS (iOS): Setting "message" together with for example "title" nullifies the "message"

### ISSUE THREAD

**Issue by leetal** [appleboy/gorush#554]
So, after digging a little i found out that if you use the default notification payload values `Title` and `Message` together, the `Message`-part of the APNS-payload is nulled. 

Essentially, if just setting the `Message` and **NOT** the `Title`, the APNS payload to the APNS servers will look like:
`{"aps":{"alert":"hello"}}` (where `Message=hello`)

**BUT**

Setting **BOTH** `Title` and `Message` will cause the payload to look like the following to APNS:
`{"aps":{"alert":{"title":"hello"}}}` (where `Title=hello`, `Message=world`)

See #553 for proposed solution.

**Comment by appleboy** [comment]
closed via #553
