### ISSUE TITLE
APNS push notification with different APNS push server info via Web API

### ISSUE THREAD

**Issue by SanghoYang** [appleboy/gorush#566]
Hi,
`gorush` is a great solution. Thank you all who contribute this project.

Here is my question or suggestion.

For Android(FCM) push: I specified a FCM server key(`android:` - `apikey`) in `config.yml` before I started `gorush`. Then, I didn't have to include the server key of `"api_key"` in JSON body of the FCM POST API whenever I sent a FCM push. But, if I specify a different server key of `"api_key"`, I could send a FCM push of a different app. This is exactly what I want.

But, for iOS push: I specified an APNS server info like `ios:` - `key_path`, `key_type`, `key_id`, and `team_id`. Then, I could send an APNS push successfully. Now, I'd like to find a way of sending an APNS push of a different app with different server info specified in JSON body of the APNS POST API like FCM push case above, which doesn't seem possible in the current `gorush`.

What do you think?

**Comment by keremoge** [comment]
For now it is configured to push notifications for all your iOS Apps in same Team id just by one config, But if you have different Account/Brand you should add one more **gorush** instance for that.

1. _gorush_Team1_ image with Team1 config
2. _gorush_Team2_ image with Team2 config

**Comment by SanghoYang** [comment]
Thanks, @keremoge . But, my suggestion is for running one gorush for multiple Team ids of multiple apps and for the total number of Team ids is not specified.

**Comment by linuxpham** [comment]
You can try at: https://github.com/miczone/gorush

**Comment by SanghoYang** [comment]
Thanks for this, @linuxpham . I will leave feedback after I try.

**Comment by linuxpham** [comment]
@SanghoYang : is it work ?

**Comment by SanghoYang** [comment]
@linuxpham I'm sorry but I had no chance to use it. And, I'm afraid that I would have no chance in the future because the development plan was changed. Thanks to your contribution and reminding me of this.
