### ISSUE TITLE
Add Decoupled Queue Support

### ISSUE THREAD

**Issue by danthegoodman1** [appleboy/gorush#575]
A really good feature that https://github.com/pennersr/shove implements is the ability to decouple the server from the producer with a queue, allowing the producer to keep filling the queue even if the notification server is down.

A great solution to support many platforms would be to use https://gocloud.dev/howto/pubsub/subscribe

This provides a great way to support many easy to use platforms like AWS SQS, GCP PubSub, and RabbitMQ.

I think adding Redis support would be nice too.

Hopefully this is something I can work on in the future, but I don't have the bandwidth now, so I am opening this issue :)

**Comment by appleboy** [comment]
duplicated of https://github.com/appleboy/gorush/issues/125

**Comment by appleboy** [comment]
Gorush supports NSQ and NATS in the `master` branch now. See the detailed information: https://github.com/appleboy/gorush/issues/599
