### ISSUE TITLE
Support of UnifiedPush

### ISSUE THREAD

**Issue by genofire** [appleboy/gorush#578]
e.g. https://gotify.net/

More Information of UnifiedPush here:
https://unifiedpush.org/

**Comment by karmanyaahm** [comment]
For some more context, to gorush, UnifiedPush is a provider like FCM, APNS, etc. but it allows self-hosting the push server. The [server specification](https://unifiedpush.org/spec/server/) is here. A (much more basic than gorush) gateway - also in Go - is [here](https://github.com/UnifiedPush/common-proxies). The "gateway" from an application server to the push provider is what I understand gorush does AFAICT.

**Comment by keremoge** [comment]
it will not support iOS pushes, right?

**Comment by karmanyaahm** [comment]
> it will not support iOS pushes, right?

Not right now, because iOS doesn't allow running user apps in the background. Currently support is for Android and Linux-like platforms.

**Comment by p1gp1g** [comment]
The server <-> server API is web push, so this is a duplicate of #248

**Comment by appleboy** [comment]
move to #248
