### ISSUE TITLE
BUG: "panic: refresh token fail"

### ISSUE THREAD

**Issue by keremoge** [appleboy/gorush#582]
There is a recent bug at huawei token refresh.You can see **`panic: refresh token fail`** at your logs.

Recently [HMS-Core](https://github.com/HMS-Core/hms-push-serverdemo-go) team made a fix: https://github.com/HMS-Core/hms-push-serverdemo-go/commit/afaab2fe7dd4cfcaa82a043cd65bbc5677117f6c

But **[gorush](https://github.com/appleboy/gorush)** uses forked version of above repository: [go-hms-push](https://github.com/msalihkarakasli/go-hms-push)
there is a recent PR on [go-hms-push](https://github.com/msalihkarakasli/go-hms-push) repo but not yet merged : https://github.com/msalihkarakasli/go-hms-push/pull/3

@msalihkarakasli should merge it and than update gorush project. If not we should use this forked version: https://github.com/stefrerichs/go-hms-push

**Comment by keremoge** [comment]
related to #555

**Comment by appleboy** [comment]
I will set the Huawei config as `disabled by default.

https://github.com/appleboy/gorush/blob/45be946f54745c6f829453542993ef33d16407e7/config/config.go#L60

**Comment by quantonganh** [comment]
We are using version:

```
	github.com/msalihkarakasli/go-hms-push v0.0.0-20210731212030-00e7b986815b
```

and still got this error:

```
panic: refresh token fail

goroutine 35 [running]:
github.com/appleboy/gorush/notify.GetPushClient.func1()
	/go/pkg/mod/github.com/appleboy/gorush@v1.16.0/notify/notification_hms.go:29 +0x89
sync.(*Once).doSlow(0x2?, 0xc0003178c0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/appleboy/gorush/notify.GetPushClient(0xc000675400?)
	/go/pkg/mod/github.com/appleboy/gorush@v1.16.0/notify/notification_hms.go:26 +0x46
github.com/appleboy/gorush/notify.InitHMSClient(0x0?, {0xc000625440?, 0xc00048fd00?}, {0xc0003bac40?, 0x1?})
	/go/pkg/mod/github.com/appleboy/gorush@v1.16.0/notify/notification_hms.go:56 +0x117
```

**Comment by quantonganh** [comment]
As you can see, we are using v1.16.0 and it include that `replace` already: https://github.com/appleboy/gorush/blob/v1.16.0/go.mod#L111

**Comment by keremoge** [comment]
> Since we are also using something from "github.com/msalihkarakasli/go-hms-push/push/core", I applied same fix as you suggested:
> 
> ```
> replace github.com/msalihkarakasli/go-hms-push => github.com/spawn2kill/go-hms-push v0.0.0-20211125124117-e20af53b1304
> ```
> 
> I have also tried updating to v1.16.2 but still encountered the same error:
> 
> ```
> panic: refresh token fail
> 
> goroutine 19 [running]:
> github.com/appleboy/gorush/notify.GetPushClient.func1()
> 	/go/pkg/mod/github.com/appleboy/gorush@v1.16.2/notify/notification_hms.go:29 +0x89
> sync.(*Once).doSlow(0x2?, 0xc0005fb530?)
> 	/usr/local/go/src/sync/once.go:74 +0xc2
> sync.(*Once).Do(...)
> 	/usr/local/go/src/sync/once.go:65
> github.com/appleboy/gorush/notify.GetPushClient(0xc0005e4400?)
> 	/go/pkg/mod/github.com/appleboy/gorush@v1.16.2/notify/notification_hms.go:26 +0x46
> github.com/appleboy/gorush/notify.InitHMSClient(0x0?, {0xc0005de840?, 0xc00034ca80?}, {0xc0004aea70?, 0x1?})
> 	/go/pkg/mod/github.com/appleboy/gorush@v1.16.2/notify/notification_hms.go:56 +0x117
> bitbucket.org/gotoko/notification/pkg/provider/push_notif.New({0x1af2b28, 0xc00034ca80}, {0x1afa2a0, 0xc0000b5ce0}, {0x1763d7f, 0x2}, 0xc000131a10)
> 	/usr/src/app/pkg/provider/push_notif/push_notif.go:128 +0x7d5
> ```

I checked again, it seems to be right fork and compatible to https://github.com/HMS-Core/hms-push-serverdemo-go, when I try I did not get the refresh token error, interesting case.

Can you please try to remove following line and run -> `go get github.com/msalihkarakasli/go-hms-push@master` to use latest commit of msalihkarakasli fork, because it also should work now;

remove this:
https://github.com/appleboy/gorush/blob/ded3bb5854ae13f5c81d2bc646660493bede0649/go.mod#L114

**Comment by quantonganh** [comment]
@keremoge If I do that, it back to the before as the latest version I'm using is [00e7b986815b](https://github.com/karakasli/go-hms-push/commit/00e7b986815b63ffd77f952d82b3416a1c5afbaa).

**Comment by keremoge** [comment]
> @keremoge If I do that, it back to the before as the latest version I'm using is [00e7b986815b](https://github.com/karakasli/go-hms-push/commit/00e7b986815b63ffd77f952d82b3416a1c5afbaa).

give me few days I will try again

**Comment by appleboy** [comment]
We can back to using https://github.com/HMS-Core/hms-push-serverdemo-go library and not use the fork version.

**Comment by keremoge** [comment]
> https://github.com/HMS-Core/hms-push-serverdemo-go

yes indeed

**Comment by appleboy** [comment]
I need to fork [HMS-Core/hms-push-serverdemo-go](https://github.com/HMS-Core/hms-push-serverdemo-go) to my account since the original repo doesn't support the go module.
