### ISSUE TITLE
Using p8 in webapi

### ISSUE THREAD

**Issue by dewf4ff** [appleboy/gorush#588]
Hi,
I want gorush to use for different apps. Can I send p8 via webapi for different apps?

Maybe I can pass teamId, keyId and keyPath via web api? And store different certs locally.

**Comment by keremoge** [comment]
No, for now you can't pass teamId+keyId+certificate via web api,
If your apps are in same account/Team, than all your apps can use same teamId+keyId+certificate, 

but if you have an app in another account/team than for now you should **multiply** gorush services;

**_myGorushService1_** service for team1 with team1 configs and **_myGorushService2_** service for team2 with team2 configs.

**Comment by dewf4ff** [comment]
Thanks
