### ISSUE TITLE
HMS Push notifications issues

### ISSUE THREAD

**Issue by SpaWn2KiLl** [appleboy/gorush#644]
While using HMS Push notifications with GoRush 1.14.0 I've identified some issues.

The first one was GoRush doesn't send `AndroidNotification` data when `huawei_data` is sent

After fixing it I've faced another issue: `foreground_show` variable was not being sent with `false` to HMS services which leads to the application always showing OS notification even when it is in foreground.

The first issue is fixed by removing [this](https://github.com/appleboy/gorush/blob/master/notify/notification_hms.go#L115) `else`.

The second issue depends on a fix on [github.com/msalihkarakasli/go-hms-push](https://github.com/msalihkarakasli/go-hms-push) lib. I already created a [PR](https://github.com/msalihkarakasli/go-hms-push/pull/4) to fix it.

This issue is probably related to #615

**Comment by appleboy** [comment]
fixed in #645 Please try the latest version.

**Comment by SpaWn2KiLl** [comment]
Just tested latest version, seems to be working properly for my use case! Thanks :)
