### ISSUE TITLE
push notification for Huawei. invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lphhh** [appleboy/gorush#651]
notification_hms.go:133 
notification_hms.go:197 
main.go:256 
in master branch.

**Comment by appleboy** [comment]
@lphhh Please describe more detailed information.

**Comment by annthonite** [comment]
Following up on this issue. I also encountered it 

DEBU[2022/01/28 - 18:07:06] Start push notification for Huawei           
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1055e51c4]

goroutine 1 [running]:
github.com/appleboy/gorush/notify.GetHuaweiNotification(0x1400063f998)
	/private/tmp/gorush-20220127-65387-ttmq22/src/github.com/appleboy/gorush/notify/notification_hms.go:133 +0x584
github.com/appleboy/gorush/notify.PushToHuawei(0x1400063f998, 0x1400020b000)
	/private/tmp/gorush-20220127-65387-ttmq22/src/github.com/appleboy/gorush/notify/notification_hms.go:197 +0x2c0
main.main()
	/private/tmp/gorush-20220127-65387-ttmq22/src/github.com/appleboy/gorush/main.go:237 +0x1948

**Comment by appleboy** [comment]
@annthonite  for latest version in master branch?

**Comment by annthonite** [comment]
yes, in master branch

**Comment by appleboy** [comment]
fixed by https://github.com/appleboy/gorush/pull/660
