### ISSUE TITLE
Worker panics, when using NATS queue due to missing metric

### ISSUE THREAD

**Issue by bancsdani** [appleboy/gorush#653]
Gorush creates a nats worker when set in the config here:
https://github.com/appleboy/gorush/blob/3f411ebe8992d151399f00645f94f506b04ccbb8/main.go#L342
the problem is, it is not setting the metric member of the worker, and when `incBusyWorker(),` `decBusyWorker()` and `BusyWorkers()` is called, we get a panic since metric is nil. Then for each message, a worker stops until we receive the number of messages as many workers we have, then just messages won't be handled. Am I missing something, something maybe in the  config, or is this an actual bug?

**Comment by appleboy** [comment]
@bancsdani I will take it.

**Comment by appleboy** [comment]
@bancsdani Fixed in master branch. Please try it out.
