### ISSUE TITLE
KeyPath can't contain a dot when deploying with Terraform 

### ISSUE THREAD

**Issue by Timac** [appleboy/gorush#668]
**Description**

GoRush uses the `KeyPath` file extension in order to determine how to create the certificate (.p12, .pem, .p8). However if you use Terraform to deploy GoRush, the name of `volume_mounts` can only contain alphanumeric characters, hyphens and underscores but no dots. This seems to make it impossible to deploy GoRush with Terraform and mount a `KeyPath` file from the GCP Secret Manager.

See here for the code: https://github.com/appleboy/gorush/blob/87c2977f6a4262843ba69562bdaeb1fdfb538069/notify/notification_apns.go#L63

**Steps to reproduce**

1. Create an `ios-app-key` secret in GCP Secret Manager containing the .p8 data
2. In your Terraform file, try to mount the file `/app-keys/ios-app-key.p8` with the p8 secret:

```
  template {
    spec {
      volumes {
        name = "ios-app-key.p8"
        secret {
          secret_name = data.google_secret_manager_secret_version.ios-app-key.secret
        }
      }

      containers {
        image = "gcr.io/xxxxxxxxxx"

        volume_mounts {
          name       = "ios-app-key.p8"
          mount_path = "/app-keys"
        }
      }
    }
  }
```

Result: When you apply the Terraform changes, you will get an error

```
│ Error: Error creating Service: googleapi: Error 400: spec.template.spec.containers[0].volume_mounts[0].name: should only have alphanumeric characters, hyphens and underscores
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "should only have alphanumeric characters, hyphens and underscores",
│         "field": "spec.template.spec.containers[0].volume_mounts[0].name"
│       }
│     ]
│   }
│ ]

```

3. Change the mounted file path from `/app-keys/ios-app-key.p8` to `/app-keys/ios-app-key`

```
  template {
    spec {
      volumes {
        name = data.google_secret_manager_secret_version.ios-app-key.secret
        secret {
          secret_name = data.google_secret_manager_secret_version.ios-app-key.secret
        }
      }

      containers {
        image = "gcr.io/xxxxxxxxxx"

        volume_mounts {
          name       = data.google_secret_manager_secret_version.ios-app-key.secret
          mount_path = "/app-keys"
        }
      }
    }
  }
```

Result: You can deploy with Terraform but then GoRush will fail with the error `Cert Error:wrong certificate key extension`

**Expected Result**

There should be no incompatibility between Terraform and GoRush. Once simple solution would be to allow `KeyPath` to have no extension and to fallback to `KeyType` to determine the type.

I would suggest to change the code at https://github.com/appleboy/gorush/blob/87c2977f6a4262843ba69562bdaeb1fdfb538069/notify/notification_apns.go#L63 from

```
		if cfg.Ios.KeyPath != "" {
			ext = filepath.Ext(cfg.Ios.KeyPath)
```

to

```
		if cfg.Ios.KeyPath != "" {
			ext = filepath.Ext(cfg.Ios.KeyPath)
			if ext == "" {
				// If the file has no extension, use KeyType
				// This makes it possible to deploy GoRush with Terraform where the name of volume_mounts can only contain alphanumeric characters, hyphens and underscores but no dots
				ext = "." + cfg.Ios.KeyType
			}
```

**Comment by appleboy** [comment]
@Timac maybe you should try `KeyBase64` config load from terraform in GCP Secret Manager

https://github.com/appleboy/gorush/blob/c81a316047ac6d736aff359c30156f726e6f6241/notify/notification_apns.go#L81-L88

**Comment by Timac** [comment]
@appleboy Thanks for the suggestion. I could indeed save the base64 key in GCP Secret Manager. However I don't know how I could then load this secret from GCP Secret Manager to set `KeyBase64`.

As far as I know, GoRush expects the `key_base64` value to be set in its YAML config file:
https://github.com/appleboy/gorush/blob/87c2977f6a4262843ba69562bdaeb1fdfb538069/config/testdata/config.yml#L70

I would somehow need to read the secret from GCP Secret Manager, then inject the base64 key inside the YAML configuration. I don't know if this is even possible…

Or do you know an alternative solution to set `KeyBase64`? Is there a way to load it as an environment variable?

**Comment by appleboy** [comment]
Use env variable like https://github.com/appleboy/gorush/issues/398#issuecomment-472504120

`GORUSH_IOS_KEY_BASE64`

**Comment by Timac** [comment]
Thanks a lot @appleboy !

Using `GORUSH_IOS_KEY_BASE64` works perfectly. I will close this ticket since there is a good existing solution.
