### ISSUE TITLE
APNs token based connection

### ISSUE THREAD

**Issue by ivandotv** [appleboy/gorush#685]
Is token-based authentication to the APNs server supported?
Is don't see any configuration options for that, looking at the issues I see that it was supported back in 2017.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

**Comment by andrhamm** [comment]
> Support p8, p12 or pem format of iOS certificate file.

Token authentication with APNS is "p8"
