### ISSUE TITLE
Redis memory is not getting released even after notifications are sent.

### ISSUE THREAD

**Issue by sankethkini** [appleboy/gorush#689]
Hello,
I am using `redis` for the queue. I found that the used memory of the redis for the queue is not getting released even after all the notifications are sent successfully. Also, I have tried to restart the Gorush program, but still the memory is not released. 
@appleboy Can you please help us resolve the issue?

<img width="628" alt="Screenshot 2022-09-08 at 2 43 59 PM" src="https://user-images.githubusercontent.com/51857698/189085526-ada2d224-14fd-4b62-93b3-a8dfd11126e4.png">

**Comment by sankethkini** [comment]
@appleboy how can I evict the old records from redis once their work is done.

**Comment by appleboy** [comment]
I will take it.

**Comment by sankethkini** [comment]
@appleboy we have fixed this issue as per our usecase. Kindly refer this pr : https://github.com/golang-queue/redisdb-stream/pull/16

**Comment by appleboy** [comment]
@sankethkini Please help to try the master version. I will bump the new version if ok.
