### ISSUE TITLE
On 1.16 release binary 'gorush --version' returns 'No Version Provided'

### ISSUE THREAD

**Issue by dbppf** [appleboy/gorush#713]
[root@ip-10-10-1-42 ec2-user]# gorush --version
GoRush No Version Provided, Compiler: gc go1.19.4, Copyright (C) 2019 Bo-Yi Wu, Inc.
[root@ip-10-10-1-42 ec2-user]#

**Comment by 53jk1** [comment]
I think that Gorush does not have a configuration file and all the information is passed through environment variables. Try to configure it.

**Comment by dbppf** [comment]
Hello @53jk1   Thanks for taking a look at this.    We do have a config.yml in place.  Here are some commands to give you a better picture.   We are currently running gorush from within the same directory where I'm trying to obtain the version.


`i-0b7bcfb3a773c5f9f():~$ pwd
/home/ec2-user
i-0b7bcfb3a773c5f9f():~$
i-0b7bcfb3a773c5f9f():~$ ls -al
total 30100
drwx------ 4 ec2-user ec2-user      273 Jan 20 17:21 .
drwxr-xr-x 3 root     root           22 Jan 12 13:42 ..
-rw-r--r-- 1 root     root          257 Jan 12 13:44 AuthKey_W8WW7H5358.p8
drwxr-xr-x 2 ec2-user ec2-user       20 Jan 12 13:44 .aws
-rw------- 1 ec2-user ec2-user      366 Jan 20 17:21 .bash_history
-rw-r--r-- 1 ec2-user ec2-user       18 Jul 15  2020 .bash_logout
-rw-r--r-- 1 ec2-user ec2-user      193 Jul 15  2020 .bash_profile
-rw-r--r-- 1 ec2-user ec2-user      391 Jan 12 13:44 .bashrc
-rw-r--r-- 1 root     root         2755 Jan 12 13:44 config.yml
-rwxr-xr-x 1 ec2-user      123 25755648 Dec 24 14:05 gorush
-rw------- 1 ec2-user ec2-user        0 Jan 12 13:44 gorush_access.log
-rw------- 1 ec2-user ec2-user  5025186 Jan 26 16:32 gorush_error.log
-rw------- 1 ec2-user ec2-user       85 Jan 12 14:27 nohup.out
drwx------ 2 ec2-user ec2-user       29 Jan 12 13:42 .ssh
-rw-r--r-- 1 ec2-user ec2-user      117 Jan 12 13:44 .user-data-vars
-rw------- 1 ec2-user ec2-user      800 Jan 20 17:21 .viminfo
i-0b7bcfb3a773c5f9f():~$
i-0b7bcfb3a773c5f9f():~$ whoami
ec2-user
i-0b7bcfb3a773c5f9f():~$
i-0b7bcfb3a773c5f9f():~$ ps -ef | grep gorush
ec2-user 11534     1  1 Jan12 ?        03:53:13 /home/ec2-user/gorush
ec2-user 22346 22311  0 16:34 pts/0    00:00:00 grep --color=auto gorush
i-0b7bcfb3a773c5f9f():~$
i-0b7bcfb3a773c5f9f():~$ ./gorush --version
GoRush No Version Provided, Compiler: gc go1.19.4, Copyright (C) 2019 Bo-Yi Wu, Inc.
i-0b7bcfb3a773c5f9f():~$`

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@dbppf try the v1.6.2 release.
