### ISSUE TITLE
Don't you create a docker image of semver only?

### ISSUE THREAD

**Issue by mitoma** [appleboy/gorush#720]
I used semver only tag in gorush.
However, the tag currently registered is the style `<semver>-os-arch`.
It would be helpful if the semver only tag was registered as before.

```
# expect
docker pull appleboy/gorush:1.16.0
# now
docker pull appleboy/gorush:1.16.0-linux-amd64
```

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
@mitoma Please try `docker pull appleboy/gorush:1.16.1`

**Comment by mitoma** [comment]
@appleboy I was able to pull successfully. thank you!
