### ISSUE TITLE
Scaling Gorush

### ISSUE THREAD

**Issue by ColeTownsend** [appleboy/gorush#733]
Has anyone had success with horizontally scaling GoRush? I've gotten to sending about 5000 notifications/sec but would love to be able to process closer to 20,000 much like the APNS2 benchmarks: https://github.com/sideshow/apns2/wiki/APNS-HTTP-2-Push-Speed#results

**Comment by appleboy** [comment]
move to https://github.com/appleboy/gorush/issues/411
