### ISSUE TITLE
v1.16.3 image does not deliver notifications but v1.16.2 w same config

### ISSUE THREAD

**Issue by vivekvenkatram** [appleboy/gorush#744]

**Comment by appleboy** [comment]
error message?

**Comment by joekohlsdorf** [comment]
Try to pass the `-c /config.yml` parameter.
I was pulling my hair out for a few hours until I realized that for some reason the latest version doesn't read my config file without this.

**Comment by appleboy** [comment]
@joekohlsdorf try the stable version v1.18.2
