### ISSUE TITLE
Firebase migrating to the HTTP v1 API 

### ISSUE THREAD

**Issue by sankethkini** [appleboy/gorush#759]
- It is seen that firebase is effectively deprecating the legacy http protocol to send, removing it from JAN 2024
- We have to [migrate](https://firebase.google.com/docs/cloud-messaging/http-server-ref) to HTTP v1 API. 

@appleboy please update if we are planning to migrate

<img width="967" alt="image" src="https://github.com/appleboy/gorush/assets/51857698/f3e98f6a-8a44-4b50-99f0-f6af373f101d">

**Comment by appleboy** [comment]
@sankethkini Yes, I will take it. Please move to https://github.com/appleboy/gorush/issues/550 for further discussion.
