### ISSUE TITLE
Is project still alive?

### ISSUE THREAD

**Issue by alikhanz** [appleboy/gorush#761]
Hello! 
I see some merged PRs, but there is not releases about year. Why?

**Comment by alikhanz** [comment]
@appleboy

**Comment by alikhanz** [comment]
Maybe i can help with releases?

**Comment by appleboy** [comment]
@alikhanz I will release asap for the new version.

**Comment by appleboy** [comment]
https://github.com/appleboy/gorush/tree/v1.17.0
