### ISSUE TITLE
incorrect version of package in go.mod

### ISSUE THREAD

**Issue by JustRomarik** [appleboy/gorush#763]
Hi
I have a problem with load module version v1.17.0, because in `go.mod` the specified version of the module `github.com/msalihkarakasli/go-hms-push v0.0.0-00010101000000-000000000000` is incorrect. 
with v1.16.3 i dont have this problem

**Comment by appleboy** [comment]
@JustRomarik I will take it.

**Comment by appleboy** [comment]
@JustRomarik try https://github.com/appleboy/gorush/releases/tag/v1.18.1
