### ISSUE TITLE
Latest docker build issue with missing fcm credential data?

### ISSUE THREAD

**Issue by khalilsarwari** [appleboy/gorush#768]
I am trying to set via environment variables in my docker-compose, I have tried:

```
GORUSH_ANDROID_KEYPATH
GORUSH_ANDROID_CREDENTIALS
GORUSH_ANDROID_KEY_PATH
```

None of the above work, I still get `missing fcm credential data`

I think I am making a silly mistake, any ideas?

I tried looking through the latest changes: [https://github.com/appleboy/gorush/pull/767](https://github.com/appleboy/gorush/pull/767)

**Comment by appleboy** [comment]
@khalilsarwari Try

```sh
export GORUSH_ANDROID_KEY_PATH =YOUR_CREDENTIALS_KEY_PATH
# or
export GORUSH_ANDROID_CREDENTIAL=$(cat fcm-demo-88b40-firebase-xxxxxx.json)
```

Thanks.

**Comment by vladcorn** [comment]
hi)
i try to update docker-compose with this env, but i still have this issue
"project ID is required to access Firebase Cloud Messaging client", do you have any idea?

```docker-compose.yaml
version: "3.7"

services:
  fintech-go-rush:
    container_name: go-rush
    image: appleboy/gorush:latest
    restart: always
    volumes:
      - './gorush/config.yaml:/config.yaml'
    environment:
      - GORUSH_ANDROID_CREDENTIAL=$(cat ./gorush/key.json)
    ports:
      - "26080:8088"
```
