### ISSUE TITLE
Addressing FCM Credentials for the gorush v.1.18.1

### ISSUE THREAD

**Issue by obuzyig** [appleboy/gorush#771]
Hello everyone,

While I am trying to start the new version of the application, I cannot provide the authorization between the application and the Firebase. I uploaded json files to the same main directory of the project.

- I have tried to write the path of the file to the GOOGLE_APPLICATION_CREDENTIALS field in the environmental variables.
- I have tried to write the path of the file to the KeyPath field with config.yml and config.go files at the same time.
- I have tried to write the json context with conversion of yaml syntax, to the Credentials field with config.yml and config.go files at the same time. (I tried it also with the JSON syntax as well.)

Is there anyone experienced the same situation or is there any suggestion that I can apply? (About the directory, about the json data, etc.)

Kind regards.

**Comment by appleboy** [comment]
How do you run the gorush application? k8s or single binary? Any output log?

**Comment by obuzyig** [comment]
> How do you run the gorush application? k8s or single binary? Any output log?

It does not work on Kubernetes.

- 2024-06-12T19:30:52.82+0300  {"level":"info","msg":"Init App Status Engine as memory","time":"2024-06-12T16:30:52Z"}
- LOG 2024-06-12T19:30:52.82+0300 {"level":"error","msg":"It will go into the WithCredentialsFile Method cfg.Android.KeyPath : /gorush-push-notification/mobile-replatform-firebase-adminsdk-ug9lr-977cb0f9ab.json","time":"2024-06-12T16:30:52Z"}
- LOG 2024-06-12T19:30:52.82+0300 {"level":"error","msg":"It will go into the cfg.Android.Credential. : ","time":"2024-06-12T16:30:52Z"}
- 2024-06-12T19:30:52.82+0300 {"level":"fatal","msg":"project ID is required to access Firebase Cloud Messaging client","time":"2024-06-12T16:30:52Z"}

```
logx.LogError.Error("It will go into the WithCredentialsFile Method : "+cfg.Android.KeyPath)
	if cfg.Android.KeyPath != "" && fileExists(cfg.Android.KeyPath) {
		logx.LogError.Error("It is in the WithCredentialsFile Method " + cfg.Android.KeyPath)
		opts = append(opts, fcm.WithCredentialsFile(cfg.Android.KeyPath))
	}
	logx.LogError.Error("It will go into the cfg.Android.Credential. : "+cfg.Android.Credential)
	if cfg.Android.Credential != "" {
		logx.LogError.Error("It is in the cfg.Android.Credential " + cfg.Android.Credential)
		opts = append(opts, fcm.WithCredentialsJSON([]byte(cfg.Android.Credential)))
	}
```

**Comment by obuzyig** [comment]
Hi, I accomplished to run it with the correction of the CI platform naming rules. Thank you.

Now I am trying to solve the problem below.

unknown error while making an http call: Post "https://fcm.googleapis.com/v1/projects/edited/messages:send": oauth2: cannot fetch token: parse " https://oauth2.googleapis.com/token": first path segment in URL cannot contain colon

**Comment by appleboy** [comment]
@obuzyig Has your problem been resolved?

**Comment by obuzyig** [comment]
> @obuzyig Has your problem been resolved?

Yes, it seems like problem was about the platform which the app is integrated. It is still not possible to address the file path right now, however, it's possible to use the other option. Thank you for your kindness and interest.
