### ISSUE TITLE
Cannot sent notification to IOS with API /api/push

### ISSUE THREAD

**Issue by tockzazazx** [appleboy/gorush#807]
I run docker with appleboy/gorush:1.18

postman:
<img width="1259" alt="image" src="https://github.com/user-attachments/assets/ea2acfb2-5fb1-44ed-96a7-ae9361345f18">

log:
<img width="871" alt="image" src="https://github.com/user-attachments/assets/92338b0b-ee7d-4b20-aec2-2fd74c175542">

but when i exec into container and use gorush command it work fine
<img width="752" alt="image" src="https://github.com/user-attachments/assets/6af21fb4-5625-4e0b-a58a-cf7c294e5f4f">

have any idea to solve this

**Comment by tockzazazx** [comment]
my bad it wrong config old after I check /api/config it not my config and every thing that I do change config map in Dockerfile in this pic:
<img width="339" alt="image" src="https://github.com/user-attachments/assets/512d9528-d893-4fc0-b013-9ba883ce9d26">

**Comment by GonzaloAvilez** [comment]
check all your configs and verifiy your certificates are well routed

**Comment by S0rc3r3r** [comment]
I have the same issue my docker file:
`version: "3.8"
services:
  telios-gorush:
    image: appleboy/gorush
    volumes:
      - ./gorush/ios-auth-key.p8:/home/gorush/ios-auth-key.p8
      - ./gorush/fcm.json:/home/gorush/fcm.json
      - ./gorush/config2.yml:/home/gorush/config.yml      
    restart: always
    ports:
      - '8088:8088'
    mem_limit: 1g
    mem_reservation: 512m
    environment:
      - GORUSH_CORE_QUEUE_NUM=512
      - GOOGLE_APPLICATION_CREDENTIALS=/home/gorush/fcm.json`
When sending the notification from the container it works:
` gorush -ios -m "test123" -t "038f8ca9e19e61070f04e67dfe36852ed15880487c44929c033dcc18074f1cdc" --topic "my.topic" -production
Using config file: /home/gorush/config.yml
INFO[2024/09/06 - 15:43:55] Init App Status Engine as memory             
DEBU[2024/09/06 - 15:43:55] Start push notification for iOS              
INFO[2024/09/06 - 15:43:55] | succeeded-push | ios [**********9e61070f04e67dfe36852ed15880487c44929c033dcc**********] test123 `

but when notification is sent via **api/push** i can see only this line in the logs and no notification is received on the device:
`3:40PM INF Request body_size=37 ip=172.24.1.2 latency=0.272153 method=POST path=/api/push status=200 user_agent=insomnia/9.3.3
`
