### ISSUE TITLE
Firewall rules setup for GoRush

### ISSUE THREAD

**Issue by mkuznetsov** [appleboy/gorush#811]
We put GoRush on server but needed to setup firewall rules. Right now I can't identify exactly number of domains to add to whitelist. 

For FCM we added: fcm.googleapis.com, www.googleapis.com, account.google.com, oauth2.googleapis.com. But looks like we need something more.

But in logs still get timeout, no detailed information about endpoint gorush get timeout on. How can we identify particular domain I need to add to white list? 

Can anybody share list of domains for firewall rules for FCM and Huawei?

**Comment by appleboy** [comment]
https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall
