### ISSUE TITLE
Alpine Image Update Question

### ISSUE THREAD

**Issue by Jake-Kuznicki** [appleboy/gorush#820]
I noticed that awhile ago the main repo was updated to conform to the new Firebase API for sending notifications. I just wanted to confirm if the alpine docker image of gorush is also updated to include the new way to set FMC credentials instead of an API Key. 

Please let me know if I missed something!

**Comment by appleboy** [comment]
docker image has been updated. https://github.com/appleboy/gorush#send-android-notification
